### ISSUE TITLE
FilenameCapitalizationWindowsScenarioTest fails on Windows

### ISSUE THREAD

**Issue by vadimpanin** [syncany/syncany#112]
Just checked. I think the test should be fixed or removed.
I created a repository in case-sensitive filesystem (ext4) and added two files to it:
* HAME_HERE
* name_here

After connecting this repo in case-insensitive filesystem (NTFS) and syncing down I got these files:
* name_here
* name_here (user's conflicted copy, 23 Apr 14, 1-47 AM)

Looks like expected behavior to me.

**Comment by binwiederhier** [comment]
That the test fails on Windows is really not a big deal as long as the software behaves correctly -- which it does. From my point of view this is closed.

```
$ echo 123 > SOMEFILE.txt
$ echo 456 > somefile.txt
$ sy up
A SOMEFILE.txt                       
A somefile.txt
Sync up finished.

// "sy down" & "sy up" on Windows

$ sy down
A somefile (Philipp's conflicted copy, 19 Feb 15, 5-59 AM).txt
Sync down finished.
```
