### ISSUE TITLE
sy init -- Error while uploading file to WebDAV (via https, livedrive.com)

### ISSUE THREAD

**Issue by rfhb** [syncany/syncany#15]
Hi, I read in a Dec 20 commit that HTTPS WebDAV is not yet expected to be fully working. With latest git pull, HTTPS WebDAV does work for me with sd2.1und1.de, however raises the following error with livedrive.com when uploading a file during repo initialisation: 

```
com.github.sardine.impl.SardineException: Unexpected response (500 Internal server error)
```

I thought I could help with the debug log for 

```
sy --debug init --plugin webdav -P url=https://webdav.livedrive.com/syncanywebdav -Pusername=<username> -Ppassword='<password>' --no-encryption --no-gzip
```

which is here: [http://pastebin.com/UBf6SuAY](http://pastebin.com/UBf6SuAY). Cheers!

**Comment by yellow1912** [comment]
Not sure if I should open a new ticket but I'm running into the same issue. My server is Ubuntu 14.10 with the latest nginx and nginx webdav extension. I can connect to my webdav and upload just fine, however with syncany I'm getting something like this:
```
115.*** - - [03/Mar/2015:22:52:47 +0700] "PROPFIND /actions/ HTTP/1.1" 207 606 "-" "Sardine/UNAVAILABLE"
115.*** - - [03/Mar/2015:22:52:47 +0700] "PROPFIND /transactions/ HTTP/1.1" 207 611 "-" "Sardine/UNAVAILABLE"
115.*** - - [03/Mar/2015:22:52:47 +0700] "PROPFIND /databases/ HTTP/1.1" 207 1712 "-" "Sardine/UNAVAILABLE"
115.*** - - [03/Mar/2015:22:52:47 +0700] "PROPFIND /transactions/ HTTP/1.1" 207 611 "-" "Sardine/UNAVAILABLE"
115.*** - - [03/Mar/2015:22:52:47 +0700] "PUT /actions/action-up-ziZGKDrrhxJPSkxECuCE-1425372762910 HTTP/1.1" 201 25 "-" "Sardine/UNAVAILABLE"
115.*** - - [03/Mar/2015:22:52:47 +0700] "PROPFIND /transactions/ HTTP/1.1" 207 611 "-" "Sardine/UNAVAILABLE"
115.*** - - [03/Mar/2015:22:52:48 +0700] "PUT /transactions/transaction-2123064f HTTP/1.1" 201 25 "-" "Sardine/UNAVAILABLE"
115.*** - - [03/Mar/2015:22:52:48 +0700] "PUT /temporary/temp-lzLUh-multichunk-88fb5f5fe6d883e9a854ecc17bf5ce126495d0ee HTTP/1.1" 201 25 "-" "Sardine/UNAVAILABLE"
115.*** - - [03/Mar/2015:22:52:48 +0700] "PUT /temporary/temp-XzEdy-database-ziZGKDrrhxJPSkxECuCE-0000000003 HTTP/1.1" 201 25 "-" "Sardine/UNAVAILABLE"
115.*** - - [03/Mar/2015:22:52:48 +0700] "MOVE /temporary/temp-lzLUh-multichunk-88fb5f5fe6d883e9a854ecc17bf5ce126495d0ee HTTP/1.1" 204 0 "-" "Sardine/UNAVAILABLE"
115.*** - - [03/Mar/2015:22:52:48 +0700] "MOVE /temporary/temp-XzEdy-database-ziZGKDrrhxJPSkxECuCE-0000000003 HTTP/1.1" 204 0 "-" "Sardine/UNAVAILABLE"
115.*** - - [03/Mar/2015:22:52:48 +0700] "DELETE /transactions/transaction-2123064f HTTP/1.1" 204 0 "-" "Sardine/UNAVAILABLE"
```

**Comment by binwiederhier** [comment]
what's the issue here? I don't see a stack trace or any error messages? Can you describe the behavior? What is expected? What actually happens?

**Comment by cr0** [comment]
According to [the specs](http://www.webdav.org/specs/rfc4918.html#rfc.section.9.1.1), the response code for `PROPFIND` is wrong (expected 200, actual 207). However, 207 is a multi-status return code, so response code 200 might be wrapped inside the response.
All other status codes are as expected and never show any error. Hence, I cannot find any error message.

**Comment by yellow1912** [comment]
@binwiederhier the above is access log from nginx. Whenever I make any local changes it seems like syncany does try to push files up but no files are written to the server. I dont see anything in the nginx error log either.

I'm not sure what "Sardine/UNAVAILABLE" means in this case and if it has any significant implication?

**Comment by cr0** [comment]
"Sardine/UNAVAILABLE" is the user-agent with "UNAVAILABLE" being the suppressed version identifier.

**Comment by binwiederhier** [comment]
@yellow1912 The 2xx response codes imply that everything works perfectly. Especially the 'DELETE ../transaction..' is likely due to a successful transaction. If you start Syncany on the command line with `sy up --debug`, you can see more output on the client side; Or just check the logs at ~/.config/syncany/logs.

**Comment by yellow1912** [comment]
I hope this can be of help:

https://gist.github.com/yellow1912/a89ffb4ebb604b64ca5e

**Comment by binwiederhier** [comment]
This is a perfectly valid log without any error messages. Also the "M composer.json " and the "Sync up done" should give away that everything worked.

I think you might be expecting the wrong thing. You will not see any unencrypted files on your webdav server. You will in particular not see the composer.json file there. Syncany stores files in a repository format that is not humanly readable.

**Important**: Your log file contains "Authorization: Basic ..." headers. These contain username and password to your webdav. Please remove/edit the gist before people steal your credentials.

**Comment by yellow1912** [comment]
@binwiederhier  thank you. I will try again. I was under the impression that Syncany will store the files there, I was wrong. The login info is for an isolated local test server but I will remove just in case, thank you
