### ISSUE TITLE
Prepare *.syncany.org backend for open sourcing

### ISSUE THREAD

**Issue by pimotte** [syncany/syncany#167]
Currently, the backend to api.syncany.org is not publicly accessible because:
- It is ugly-ass php
- It has not been code-reviewed.

The backend consists of a landing php script, a cronjob, the api php and a mysql database.

It would be preferable to open source this, if you would like to pick this up, contact @binwiederhier to get the code.

**Comment by pimotte** [comment]
Is this actually done? If @otisid is not in this any more, that's not actually a reason to close the issue:)

**Comment by binwiederhier** [comment]
You got me here. I just thought it's not thaaat important, so I quietly closed it... Reopening.

**Comment by otisid** [comment]
Sorry for not being active on this issue, I got a bit overwhelmed in my personal life segment and it took it's toll :(
I'll surely try to contribute to the project in the future, but for now maybe it's best that someone else takes this issue over until things calm down at my side. Once again, sorry for the hold-up.

**Comment by pimotte** [comment]
No problem, just let us know if you'd like to pick it up again.

@binwiederhier, while I don't think this is a huge priority per se, we don't need to suffer more from What-if-Phillipp-gets-run-over-by-a-bus-syndrome than we already are:P

**Comment by binwiederhier** [comment]
So I've decided that we should do this at some point, and I've started to separate things on the server side more clearly. This is an attempt to document my progress, even though you guys can't see things yet:

Affected parts
- **syncany.org** - Main website
- **api.syncany.org** - Plugin/Shortlink/Badge API
- **get.syncany.org** - Download instructions, possibly the `dist/`-successor
- **upload.syncany.org** - Interim landing space for all uploaded files (FTP homes & cron scripts)
- **archive.syncany.org** - Target space for the .deb files (reprepro-managed APT archive)
- **docs.syncany.org** - Target space for generated JavaDoc (and possibly the userguide)
- **reports.syncany.org** - Target space for the generated reports (tests, coverage)

Decisions:
- [ ] Decide where to put `dist/`: get.syncany.org, dl.syncany.org, dist.syncany.org, download.syncany.org? Make a proper version browser? Or leave simple directory index?
- [ ] Decide whether to create one repo for all above components, or multiple. Opinions?

Actions:
- [ ] Rewrite api.syncany.org with a proper RESTful API (a la [this](http://coreymaynard.com/blog/creating-a-restful-api-with-php/))
- [ ] Rewrite PHP-based cron scripts, harmonize, class-ify, task-ify
- [ ] Move `dist/` to new location, adjust cron scripts
- [ ] Write How-To for Plugin-FTP setup 
- [ ] Write How-To for Travis-CI FTP credential encryption
- [ ] Write How-To for Apache configuration

**Comment by binwiederhier** [comment]
I've moved a bunch of stuff already, although most of it is empty: https://github.com/syncany/syncany-website / But: Lots of [progress on the API](https://github.com/syncany/syncany-website/tree/master/api.syncany.org) -- completely rewritten in 2 days!

**[PluginsController](https://github.com/syncany/syncany-website/blob/master/api.syncany.org/src/php/Syncany/Api/Controller/PluginsController.php) (all GET):**
- List (one plugin, different syntax, same result):    
  https://api.syncany.org/v3/plugins/dropbox?appVersion=0.4.3   
  https://api.syncany.org/v3/plugins?appVersion=0.4.3-alpha&pluginId=dropbox   
  https://api.syncany.org/v3/plugins/list?appVersion=0.4.3-alpha&pluginId=dropbox   
- List (many plugins, with snapshots):   
  https://api.syncany.org/v3/plugins?appVersion=0.4.3-alpha&snapshots=true
- Upload new plugins (To Do):   
   `echo somefile | curl -v -T- https://api.syncany.org/v3/plugins`

**[BadgesController](https://github.com/syncany/syncany-website/blob/master/api.syncany.org/src/php/Syncany/Api/Controller/BadgesController.php) (all GET):**
- https://api.syncany.org/v3/badges/tests
- https://api.syncany.org/v3/badges/coverage
- https://api.syncany.org/v3/badges/lines

**[LinksController](https://github.com/syncany/syncany-website/blob/master/api.syncany.org/src/php/Syncany/Api/Controller/LinksController.php):**
- GET existing link (different syntax, same result; redirects to syncany://):   
  `curl -v https://api.syncany.org/v3/links/FM8ZPiY`   
  `curl -v https://api.syncany.org/v3/links?l=FM8ZPiY`
- Add new link (POST)   
  `curl -v -d'l=syncany://2/hellothere' https://api.syncany.org/v3/links`

**Comment by binwiederhier** [comment]
The syntax is completely backward compatible, so it should work without problem with the current code base. Still To Do: Authentication on PUT calls, implement them.

**Comment by binwiederhier** [comment]
Authentication is done, plugin upload for .deb/.jar/.app.zip/.exe works (not live yet). 

Relevant branches:
- https://github.com/syncany/syncany-website/compare/feature/authentication
- https://github.com/syncany/syncany/tree/feature/api-upload

Still lots to do.

**Comment by pimotte** [comment]
I've been making some attempts at dry-reviewing this.

Couple of questions:
- Do we have a single secret hash for HMAC? Do we want to be able to have multiple for third-party API submissions?
- What purpose does the random value serve?
- Are the arguments the wrong way round in https://github.com/syncany/syncany-website/blob/develop/api.syncany.org/src/php/Syncany/Api/Controller/Controller.php#L121 ?
- Could you spread some comments through the code? The OO-PHP looks very java-y, but since we're lacking the static typing, I have no idea what a $securityContext might be.

(One final question: Do you have a recommendation for some sort of IDE for PHP?)

**Comment by binwiederhier** [comment]
ad HMAC: Every plugin has its only API key which is then used to authenticate the request:
```php
$this->authenticate("plugins-put-$pluginId", $methodArgs, $requestArgs);
```
ad third party submission: Yes, I believe that is the way to easily achieve third party submissions. Just give the plugin developer an API key and instructions how to use it. And then we mark the plugin inthe response as 3rd party.

ad random value: typically random values make the plaintext request unguessable. However, my inability to properly explain the real purpose tells me we should maybe think about OAuth1.0a to properly secure the API -- even though we're pretty close to what Oauth does already. See [this blog post](https://stormpath.com/blog/secure-your-rest-api-right-way/).

ad variable order: This is a naming issue. The API key files are stored in `config/keys` and are named `plugins-put-sftp.properties`, so the configContext is indeed "keys" while the name is "plugins-put-sftp". I've renamed it to:

```php
$apiKey = $this->readApiKey($keyName);
...
$keys = FileUtil::readPropertiesFile("keys", $keyName);
```

ad comments: Absolutely. Will do. I wanted to be sure that this is it, before documenting things.

ad IDE: PhpStorm is pretty awesome. It's based on the same code as IntelliJ IDEA. It's not free, but there are free licenses for open source developers.

**Comment by pimotte** [comment]
ad random value: My gut says the random value is not necessary. We include the time, so there shouldn't be requests that are repeated twice. Figuring out the plaintext request from the hash requires a pre-image attack on the hash function, right? As far as I am aware, HMAC does not provide encryption, so "protecting" the request is not be done by hashing, but by wrapping the whole thing in SSL.

**Comment by binwiederhier** [comment]
The time value can be easily guessed and thereby it is easy to guess the possible plaintexts. Also, both OAuth1 and OAuth2 use a nonce of some sort to prevent replay attacks (we'd actually need to store and check them somewhere though), so I feel it is best practice to do that; but yes, it might not be necessary.

I'll be looking into implementing OAuth1 for the API anyway, so this might be a moot point. My problem with all the OAuth1 libraries is that they are so heavy and that it doesn't quit match the use case. We could just use the token and token secret part of OAuth1 and ignore the rest. Then we'd basically have what we have now...

Related:
- http://php.net/manual/en/oauth.examples.fireeagle.php (Shipped with PHP!)
- http://www.slideshare.net/stormpath/secure-your-rest-api-the-right-way
- http://www.glenscott.co.uk/blog/securing-php-rest-api-oauth/

**Comment by binwiederhier** [comment]
The new API went live yesterday and all clients are now exclusively using this API. The old code still exists, but has been deactivated. /v1/ and /v2/ are redirected to /v3/.

Yeyy!

**Comment by cr0** [comment]
Hmm... redirecting v[1,2] to v3 seems wrong since it's somehow against the versioning approach.

**Comment by binwiederhier** [comment]
v3 is completely backward compatible, so there is no point in keeping the old versions. Normally I would agree, but in this case there really is no point :smile:

**Comment by cr0** [comment]
That sounds reasonable! ;)
