### ISSUE TITLE
Extend .syignore: Ability to exclude files/folders from synchronization

### ISSUE THREAD

**Issue by mihaisecasiu** [syncany/syncany#189]
There are many cases when you might want to sync an application's folder but inside the application creates some temporary files that you don't want to sync. 

Edit by Pim:

We currently have .syignore, which only works for pre-emptively ignoring. This issue is a feature request for ignoring after a file has gone in the database.

**Comment by binwiederhier** [comment]
Although not entirely identical, this is **closely related to issue #263**. If anyone wants to develop this, please make sure to check this issue!

**Comment by schnittchen** [comment]
If I remove a file which would be syignored (hadn't it already been in the system), then recreate that file somewhat later, will this be picked up, or is that not a work around?

**Comment by binwiederhier** [comment]
@schnittchen Yes that would work. I just tried it:
```
$ mv ignoreme ..
$ sydev up
D ignoreme                           
Sync up finished.
$ mv ../ignoreme .
$ sydev up
Sync up skipped, no local changes.   
```

**Comment by schnittchen** [comment]
Can't get that work-around to work in my case, which is with a directory w/ contained files.
