### ISSUE TITLE
Plugin request: OpenStack Swift

### ISSUE THREAD

**Issue by gudron** [syncany/syncany#251]
Hi guys. 
The first thing - a great utility. 
Thank you very much for it. 

Can I request to add functionality? 
It would be great to add Open Stack Swift plug-in.

Maybe you have already discussed?

**Comment by lukmanandreas** [comment]
@mlanner . i am a student. i deploy openstack swift as my final project. I use 2 computer, 1 as proxy node and 1 as storage node. The Openstack Swift is up and running. I can upload and download file from container. I installed just keystone module and swift module without other module (compute, neutron, and others). IP Address of proxy node is 167.205.64.86. My client computer can ping and ssh to proxy node, so there isn't network connectivity problem. I want to use openstack swift as backend for syncanny. I have problems.
In my swift authentication at /etc/swft/proxy-server conf, I use keystoneauth as authentication. Here is the line. 
[pipeline:main]
pipeline = authtoken cache healthcheck keystoneauth proxy-logging proxy-server

What url, user, password i use to authenticate. 
I try http://167.205.64.86, user = admin, password = pass. fail, error code 501
I try http://167.205.64.85:8080/v1, user = admin, password = pass. fail error code 501
I try http://167.205.64.85:5000/v2.0, user = admin, password = pass, fail error code 501
I try http://controller:8080/v1/AUTH_7f44897753084e718a9464b42c182374, user = 7f44897753084e718a9464b42c182374, password = 30f69b9924a24d84ba785ecebf9cdc10(auth token), fail error code 501.

Do you have any idea?
Thank you @mlanner

**Comment by mlanner** [comment]
@lukmanandreas I'm fairly certain you won't be able to use auth v1.0 with Keystone. So, you'll likely have to use v2.0, as in your http://167.205.64.85:5000/v2.0. That said, I'm not sure if the Syncany plugin was written to support both v1.0 and v2.0. I know for a fact that it works well with v1.0. Support for OpenStack v1.0 has been dropped in Keystone. The best person to answer if v2.0 is supported in the Syncany Swift plugin would probably be @cr0. I also tried to find in the code if the plugin is using OpenStack XML or JSON, but I haven't found it (yet). Again, @cr0 would probably know from the top of his head. I'll see if I can test it on one of my clients against a cluster using v2.0 auth.

**Comment by lukmanandreas** [comment]
thank you so much for the information @mlanner .
