### ISSUE TITLE
Plugin update notification and upgrade mechanism

### ISSUE THREAD

**Issue by cr0** [syncany/syncany#300]
Provide a way to notify if a new plugin is available and/or offer a way to (auto-)update them (silently).

TODO
- [x] Handle windows purgefile

**Comment by cr0** [comment]
a) Actually I missed the semver dependency so I did it myself. You can decide if we stick to semver or if we use my implementation. I think [`VersionTest`](https://github.com/syncany/syncany/blob/feature/issue300/syncany-lib/src/test/java/org/syncany/tests/util/VersionTest.java) shows what the class is capable of.

b) Done

c) I tried to implement it using a similar approach to `purge file`. Can some windows user test if it works? I don't have access on my VM at the moment.

d) I'll can also do that issue, however, I want to finish this one first.

e) I recommend to not bloat this issue since e) seems to be much more complex than upgrading a simple plugin. It will too bring some plugin api changes imho.

**Comment by binwiederhier** [comment]
ad (a): I realize that you put a lot of effort into this, and even if your library satisfies the use cases we claim to do [SemVer](http://semver.org/), and seeing that the SemVer spec is pretty thick, I think we should try to stick to a standard SemVer library. If you look at [the examples of the library](https://github.com/zafarkhaja/jsemver), you can also see that. 

ad (c): Looks good (from a dry-review point of view). I can test it when I have the time (after I moved).

ad (d)+(e): Alright.

**Comment by cr0** [comment]
a) switched back to SemVer (see 119e285f2ff3c4ea00378a9c83eba015631502d2)

**Comment by binwiederhier** [comment]
Update works on Windows and Linux; The output is a bit weird: https://gist.github.com/binwiederhier/25f476d9b2d550eb9e14

I think the output should be:

```
$ sy plugin update
Updating 'ftp' ... OK
Updating 'gui' ... OK
```

Some thoughts for this regarding the Windows batch script:
```
[22:35:29] <binwiederhier> maybe we should suppress the output of "sy plugin install" on windows.
[22:35:42] <binwiederhier> if it is called as part of "sy plugin update"
[22:36:00] <binwiederhier> ... plugin install %%b >NUL basically
[22:37:28] <binwiederhier> not sure. maybe not a good idea though. it took ages to download the gui plugin on my connection. people might think somethings broken
[22:40:56] <binwiederhier> maybe some sort of short output for "sy plugin install"
[22:41:50] <binwiederhier> how about: "sy plugin install ftp --short-output" only returns "OK" instead of the whole mumbo jumbo.
[22:42:18] <binwiederhier> then the batch script can call ^^ instead; and do something like that:
[22:42:25] <binwiederhier> Updating 'ftp' ... OK
[22:42:30] <binwiederhier> Updating 'gui' ... OK
[22:43:22] <binwiederhier> probably also a good idea for the linux output
[22:43:28] <binwiederhier> i'm complicating your life again...
```

**Comment by cr0** [comment]
Ok, we now have a minimal output option which results in:

```
PS C:\Develop\syncany\build\install\syncany\bin> .\sy.bat plugin update
Plugins to be updated: dropbox, ftp

Installing dropbox... OK
Removing dropbox... OK
Installing ftp... OK
Removing ftp... OK
PS C:\Develop\syncany\build\install\syncany\bin>
```
But I really don't know why `private void printResultRemove(PluginOperationResult operationResult)` is also triggered?! Any idea?

**Comment by binwiederhier** [comment]
Nice work! Maybe we're also writing the "purgefile"?

**Comment by cr0** [comment]
The bat file doesn't use `sy plugin remove` to uninstall a plugin, does it? It first uses a `del` command to remove the jar and then calls `sy plugin install <id> -m`. Where is this remove coming from?

**Comment by binwiederhier** [comment]
https://github.com/syncany/syncany/blob/feature/issue300/syncany-lib/src/main/java/org/syncany/operations/plugin/PluginOperation.java#L158

**Comment by cr0** [comment]
OMG, good old switch fall through got me :(
https://github.com/syncany/syncany/blob/feature/issue300/syncany-cli/src/main/java/org/syncany/cli/PluginCommand.java#L150

**Comment by binwiederhier** [comment]
Haha. Oh noo.

**Comment by cr0** [comment]
PR in the pipe
