### ISSUE TITLE
Flickr plugin for Syncany (stores data in images; 1TB storage space)

### ISSUE THREAD

**Issue by binwiederhier** [syncany/syncany#304]
I realize that this is a bit of a fun plugin, but the 1 TB or image data was just too good to be true. So here is a working [Flickr plugin](https://github.com/syncany/syncany-plugin-flickr) -- still a bit inefficient, but fully working!

Random comments:

(1) The plugin encodes data into PNG images -- which is a bit tricky (as my wonderful [PngEncoder](https://github.com/binwiederhier/syncany-plugin-flickr/blob/6ac8ec59e8275320e98b847ffc8be893e0e8cf2f/src/main/java/org/syncany/plugins/flickr/PngEncoder.java) class shows). These PNG images are them uploaded to Flickr into a previously specified album/photoset. This looks like that:

![2014121323 38 25_selection_001](https://cloud.githubusercontent.com/assets/664597/5425724/636b8204-8323-11e4-8fab-7356b1593088.png)

(2) If you want to see a multichunk in more detail, here is what it looks like (_If you look at it in a hex editor, you'll find the word `N3RD` in it -- which is what this definitely is_):

![testfile](https://cloud.githubusercontent.com/assets/664597/5425729/c224547e-8323-11e4-94a6-4510c4251ba3.png)

![2014121423 18 26_selection_001](https://cloud.githubusercontent.com/assets/664597/5429337/d636b762-83e7-11e4-95ad-9e1cc280deea.png)

(3) There are no folders. All files are stored in one album -- and since there is no filtering of the `getPhotos()` method, the whole meta data management is a bit slow right now. This could be fixed by using two albums (one for metadata, one for multichunks); or by listing only specific tag/titles/etc. (I haven't found a way to do that though).

(4) Since Flickr albums can be public, a read-only repository could be possible in the future!

(5) The plugin includes a tiny workaround for Flickr -- Too small images (< 17x17 pixels) are sometimes rejected byFlickr, even if they are encoded correctly (this also applies for GIMP-exported images). To handle this behavior, all PNGs are prepended with 867 bytes (17x17 x 3/RGB) of black pixels. Since these pixels are compressed, that's not a big deal though (+ 150 bytes or so)

(6) ~~I had to make a tiny adjustment to the `core/` in the `AbstractInitCommand`. I haven't merged that, but the plugin only works if the binary from `core/` is used.~~ It's merged. You can do `sy plugin install flickr -s`

(7) If you look at the PNG, it's a valid PNG:

```
$ identify -verbose c224547e-8323-11e4-94a6-4510c4251ba3.png 
Image: c224547e-8323-11e4-94a6-4510c4251ba3.png
  Format: PNG (Portable Network Graphics)
  Class: DirectClass
  Geometry: 220x220+0+0
  Resolution: 72x72
  Print size: 3.05556x3.05556
  Units: Undefined
  Type: TrueColor
  Endianess: Undefined
  Colorspace: sRGB
  Depth: 8-bit
  Channel depth:
    red: 8-bit
    green: 8-bit
    blue: 8-bit
  Channel statistics:
    Red:
      min: 0 (0)
      max: 255 (1)
      mean: 126.409 (0.495723)
      standard deviation: 74.2828 (0.291305)
      kurtosis: -1.2008
      skewness: 0.00387802
    Green:
      min: 0 (0)
      max: 255 (1)
      mean: 126.356 (0.495512)
      standard deviation: 74.3924 (0.291735)
      kurtosis: -1.20197
      skewness: 0.00470403
    Blue:
      min: 0 (0)
      max: 255 (1)
      mean: 126.279 (0.495212)
      standard deviation: 74.1663 (0.290848)
      kurtosis: -1.20174
      skewness: 0.00632261
  Image statistics:
    Overall:
      min: 0 (0)
      max: 255 (1)
      mean: 126.348 (0.495482)
      standard deviation: 74.2806 (0.291296)
      kurtosis: -1.20149
      skewness: 0.00496893
  Rendering intent: Perceptual
  Gamma: 0.45455
  Chromaticity:
    red primary: (0.64,0.33)
    green primary: (0.3,0.6)
    blue primary: (0.15,0.06)
    white point: (0.3127,0.329)
  Interlace: None
  Background color: white
  Border color: srgb(223,223,223)
  Matte color: grey74
  Transparent color: black
  Compose: Over
  Page geometry: 220x220+0+0
  Dispose: Undefined
  Iterations: 0
  Compression: Zip
  Orientation: Undefined
  Properties:
    date:create: 2014-12-14T23:17:52+01:00
    date:modify: 2014-12-14T23:17:52+01:00
    N3RD: 7
    png:cHRM                 : chunk was found (see Chromaticity, above)
    png:gAMA                 : gamma=0.45454544 (See Gamma, above)
    png:IHDR.bit_depth       : 8
    png:IHDR.color_type      : 2 (Truecolor)
    png:IHDR.interlace_method: 0 (Not interlaced)
    png:IHDR.width,height    : 220, 220
    png:sRGB                 : intent=0 (See Rendering intent)
    png:text                 : 1 tEXt/zTXt/iTXt chunks were found
    signature: 63ef7a099c778a8f9b81a9fb4387387ca2e76221208d96c4e41574c8db2076b0
  Artifacts:
    filename: c224547e-8323-11e4-94a6-4510c4251ba3.png
    verbose: true
  Tainted: False
  Filesize: 145KB
  Number pixels: 48.4K
  Pixels per second: 0B
  User time: 0.000u
  Elapsed time: 0:01.000
  Version: ImageMagick 6.7.7-10 2014-03-06 Q16 http://www.imagemagick.org
```

(7) Thoughts?

**Comment by tgharib** [comment]
This plugin is hilarious! Love it!

**Comment by binwiederhier** [comment]
:+1:
