### ISSUE TITLE
Confusing error message when plugin not installed "Config file does not exist or is invalid:"

### ISSUE THREAD

**Issue by binwiederhier** [syncany/syncany#328]
When a plugin is not installed and `sy (up|down|status|...)` is run, this error message is not very helpful. This should indicate that the plugin is not available:

```
$ sydev status
Error: Config file does not exist or is invalid: /home/pheckel/Syncany/Syncany Team/.syncany/config.xml
       Refer to help page using '--help'.
```

**Comment by jaltek** [comment]
Hi,
I have to reopen this issue because I'm facing the same problem now. I...
* switched from openSUSE to Arch Linux
* Installed syncany via AUR
* installed the snapshot release of the sftp plugin.
* Tried a ```syncany ls-remote``` within the already (from openSUSE) connected repo.

and got the same message:

```Config file does not exist or is invalid:/path/to/my/repo/.syncany/config.xml```

**Comment by pimotte** [comment]
What were the versions you had on openSUSE and Arch? It might be that the Config actually IS invalid (for the Arch version)

**Comment by jaltek** [comment]
Must have been 0.4.6 as far as I remeber.
Well, I trust syncany's message that the config IS invalid - but why? ;)

I don't see any messages by using the debug flag or in the logfiles.



Am 27. November 2015 15:26:20 MEZ, schrieb Pim Otte <notifications@github.com>:

**Comment by pimotte** [comment]
Can you manually inspect the file to see if there's anything wrong with it? Maybe post it with the sensitive information removed? Or do you indeed not have the correct plugin and does it function when you install the plugin?

**Comment by jaltek** [comment]
I don't see any problems:

```
<config>
   <machineName>xXXxxxXXXxxxXXXxxxxX</machineName>
   <displayName>jan</displayName>
   <masterKey salt="XXX" key="XXX"/>
   <connection class="org.syncany.plugins.sftp.SftpTransferSettings" type="sftp">
      <hostname>host.name</hostname>
      <username>user</username>
      <password encrypted="true">XXX</password>
      <path>/path/to/remote/repo</path>
      <port>77</port>
   </connection>
</config>
```

I did a fresh ```syncany connect``` in a separate folder which the same SFTP repo and this works flawlessly. I also made a ```diff``` between the "old" config.xml and the new one and the only differences are the ```<machineName>``` and the ```<password encrypted="true">``` elements.

**Comment by jaltek** [comment]
Ok, got it:

```java.io.IOException: java.lang.Exception: Integrity exception: Calculated HMAC and read HMAC do not match.```

I simply changed the [Line 89 in syncany-lib/src/main/java/org/syncany/config/to/ConfigTO.java](https://github.com/syncany/syncany/blob/abb08690abbb4ad16fe0594660deb1849a4987ca/syncany-lib/src/main/java/org/syncany/config/to/ConfigTO.java#L89) to print out the exception message

**Comment by pimotte** [comment]
Could you remove that catch block in it's entirety and let the exception bubble and post the full stacktrace you get? (Use -d if necessary)

**Comment by jaltek** [comment]
Did you mean this block?

```java
catch (Exception ex) {
   throw new ConfigException("Config file does not exist or is invalid: " + file, ex);
}
```

This won't work:

```
/home/jaltek/git/syncany/syncany-lib/src/main/java/org/syncany/config/to/ConfigTO.java:70: error: unreported exception Exception; must be caught or declared to be thrown
                        registry.bind(SaltedSecretKey.class, new SaltedSecretKeyConverter());
                                     ^
/home/jaltek/git/syncany/syncany-lib/src/main/java/org/syncany/config/to/ConfigTO.java:71: error: unreported exception Exception; must be caught or declared to be thrown
                        registry.bind(String.class, new EncryptedTransferSettingsConverter());
                                     ^
/home/jaltek/git/syncany/syncany-lib/src/main/java/org/syncany/config/to/ConfigTO.java:73: error: unreported exception Exception; must be caught or declared to be thrown
                        return new Persister(strategy).read(ConfigTO.class, file);
```

**Comment by jaltek** [comment]
Side-note: Meanwhile I was able to reproduce this issue on an other workstation (also openSUSE but I think the distro is not the root cause).

I simply installed Arch Linux in VirtualBox, installed syncany with the ```sftp``` snapshot plugin, __copied__ the already connected repo from my workstation to the virtual installation, tried a ```syncany ls-remote``` within the folder and got the same message.
