### ISSUE TITLE
use of '_' as an identifier might not be supported in releases after Java SE 8

### ISSUE THREAD

**Issue by cr0** [syncany/syncany#331]
There about 100 warnings when I compile the GUI with gradle and jdk 8 since the underscore identifier is used to provide an easy way to do i18n.

Example warning:
```
/Users/chr/Work/syncany-plugin-gui/src/main/java/org/syncany/gui/wizard/InitSuccessPanel.java:82: warning: '_' used as an identifier
		copyLinkButton.setText(_("org.syncany.gui.wizard.InitSuccessPanel.button.copyLink"));
		                       ^
  (use of '_' as an identifier might not be supported in releases after Java SE 8)
```

This is a reminder for the future.

**Comment by binwiederhier** [comment]
Fixed by https://github.com/syncany/syncany-plugin-gui/commit/4c063e1f67a4cf619c3f4db27044c7a387d0060b
