### ISSUE TITLE
Create 'Recent changes ...' menu item and/or separate panel

### ISSUE THREAD

**Issue by binwiederhier** [syncany/syncany#332]
Dropbox has a nice "Recent changes ->" menu item showing the changed and added files. I think this is very useful when multiple persons are connected to one repo. Currently we really have to guess what has changed. 

This issue relies on #298 to be created first. Possible incarnations of this:

Dropbox:
![2014123013 27 40_selection_001](https://cloud.githubusercontent.com/assets/664597/5578446/ac95258c-9027-11e4-8ae9-126888595682.png)

SparkeShare (from [here](http://i1-linux.softpedia-static.com/screenshots/SparkleShare_1.jpg)):
![2014123013 28 03_selection_001](https://cloud.githubusercontent.com/assets/664597/5578451/c04cb7e8-9027-11e4-905a-67d9e8a88a8f.png)

ownCloud (from [docs](http://doc.owncloud.org/desktop/1.7/navigating.html)):
![2014123013 29 03_selection_001](https://cloud.githubusercontent.com/assets/664597/5578456/e73be798-9027-11e4-9c6c-445c0b5d4ee4.png)

**Comment by binwiederhier** [comment]
(1) After successfully implementing `sy log` (prerequisite for this issue), I started to work on the 'recent changes' sub menu. It already works for the `DefaultTrayIcon`, but the amount of data sent via the websocket is insane compared to what we display. I'll have to think of something here... 

(2) [DatabaseVersion](https://github.com/syncany/syncany/commit/3679b22f02ba6600d5dadb223af4ebb7f5e3b601) had to be *partially* annotated with SimpleXML annotations, because we don't want to send the chunk/multichunk data over the wire. 

- Option 1: If we always want to exclude it, it should stay that way. Then `LogOperationOptions.excludeChunkData` is not necessary.
- Option 2: We make `ChunkEntry`, `MultichunkEntry`, etc. serializable and properly annotate them.

Thoughts?

Relevant commits: https://github.com/syncany/syncany-plugin-gui/commit/4e3bc4d03f41825c12fbf505b4f62b7dbf1c5e88, https://github.com/syncany/syncany-plugin-gui/commit/882169b1f847de9620c24b03fbdc181234c01b68, https://github.com/syncany/syncany/commit/3679b22f02ba6600d5dadb223af4ebb7f5e3b601

Screenshot:
![2015010300 29 30_selection_001](https://cloud.githubusercontent.com/assets/664597/5600673/c17b542a-92df-11e4-9124-0608165ea96b.png)

**Comment by binwiederhier** [comment]
This feature is ready to be merged. I'd love some feedback, either on the code as a dry-review or just to see if it works for you: https://github.com/syncany/syncany-plugin-gui/compare/feature/issue332-recent-changes

**Comment by pimotte** [comment]
I'll probably have time to look at this in the weekend.

**Comment by pimotte** [comment]
LGTM, mergeable:D

**Comment by binwiederhier** [comment]
Merged

**Comment by cr0** [comment]
The recent menu item list is missing some characters like the `&` (ampersand), it's simply ignored.

**Comment by binwiederhier** [comment]
True that. New issue for this here: https://github.com/syncany/syncany/issues/367
