### ISSUE TITLE
Preferences dialog: Managed folders, add to startup, plugin management, proxy settings

### ISSUE THREAD

**Issue by binwiederhier** [syncany/syncany#334]
At some point we'll need a settings/preferences dialog for the GUI to fulfil all the functions the GUI cannot do yet -- and to eliminate XML-file editing.

I've made some mockups. They are largely inspired by the [ownCloud settings dialog](http://doc.owncloud.org/desktop/1.7/navigating.html). Tell me what you think.

![settings_general](https://cloud.githubusercontent.com/assets/664597/5579169/8480e9f0-9036-11e4-8971-a3b1a3395ac5.png)
![settings_folder](https://cloud.githubusercontent.com/assets/664597/5579168/847ebd1a-9036-11e4-896f-5effcd8792c6.png)
![settings_network](https://cloud.githubusercontent.com/assets/664597/5579171/8482e958-9036-11e4-8ee4-0fd89c9a0cf5.png)
![settings_plugins](https://cloud.githubusercontent.com/assets/664597/5579170/84812140-9036-11e4-9551-36edcee6c394.png)

**Comment by binwiederhier** [comment]
Boom. Working perfectly (as far as I can tell!):

![Uploading 2015010122:08:25_Selection_001.png . . .]()

**Comment by binwiederhier** [comment]
"Launch at startup" now also works. For Windows it's a bit of a hack, but it's good enough. I think this might be it for this issue. The per-folder settings should be done another time. 

Some feedback would be great. Does it work? Do you have graphical issues? Anything missing?
@cr0, @pimotte, others?

**Comment by pimotte** [comment]
LGTM. At the moment I have 2 graphical issues, but I'm reasonably confident those are due to my franken-setup. The notification tooltip-balloon-thingie is completely black. Also, in the plugin selection lists (both of them) the selecting bar is white, as well as the selected text. (Hence the selected entry is not visible). I'm guessing both are related to the fact that i'm running awesome, but generated my gtk-settings with gnome, so there's some trickery involved there.

**Comment by binwiederhier** [comment]
Thanks for trying it out. The notification bubble thing happens on my system as well. I always assumed that this was a problem with my system. I'll open another issue for that, since it is not related to this issue and it was actually like this before.

Can you make a screenshot of the white selection bar?

![2015010300 47 08_selection_001](https://cloud.githubusercontent.com/assets/664597/5600754/229e6114-92e2-11e4-851a-a85db1fda0b7.png)

**Comment by pimotte** [comment]
I looked at the selection issue myself. 5f1a8c4fb6b26a3984279bf1c22d5629692aa3e1 fixes that. If that breaks something for you, let me know.

**Comment by binwiederhier** [comment]
It looks a bit different, but if that fixes it for you/others that's fine for me:

![2015010312 56 12_selection_001](https://cloud.githubusercontent.com/assets/664597/5602357/f2589040-9347-11e4-896d-a4eefabd3e01.png)

**Comment by binwiederhier** [comment]
Lets consider this closed. :)
