### ISSUE TITLE
Syncany trying to read all files on hard drive when i try install plugin

### ISSUE THREAD

**Issue by portals12** [syncany/syncany#342]
piotrek@pc1-arch ~ :( $ syncany plugin install ftp -d
debug
Application version: 0.4.0-alpha
4-1-15 17:37:18.172 | CommandLineClie | main           | INFO : Application version: 0.4.0-alpha
4-1-15 17:37:20.172 | com.google.comm | main           | WARN : Cannot read directory /home/piotrek/Other/x/sklep_o/cache/smarty/compile/be/de
4-1-15 17:37:20.172 | com.google.comm | main           | WARN : Cannot read directory /home/piotrek/Other/x/sklep_o/cache/smarty/compile/dc/e3
and long list of all of my files.

**Comment by pimotte** [comment]
I'm not sure where, but this has been fixed (I can reproduce with 0.4.0-alpha, but not with 0.4.1-alpha). Thanks for reporting:)

**Comment by binwiederhier** [comment]
I don't recall fixing that... @pimotte, any recollections where the cause for this was/is?

**Comment by pimotte** [comment]
Nope, I tried to find out, but I could not find a reason (quickly).

**Comment by binwiederhier** [comment]
I don't think we fixed anything here. This is a problem with the Guava library and the `ClassPath` helper we use in [Plugins.loadPlugins()](https://github.com/syncany/syncany/blob/93b0292a2249f0231d3ac7700718c276b70de9fc/syncany-lib/src/main/java/org/syncany/plugins/Plugins.java#L140). In [line 306](http://docs.guava-libraries.googlecode.com/git-history/v15.0/javadoc/src-html/com/google/common/reflect/ClassPath.html#line.306) of that this message is outputted in the `scanDirectory()` method. In particular, `ClassPath.from(Thread.currentThread().getContextClassLoader())` seems to call this method and thereby cause the problems. 

I have no idea what is different with @portals12's setup or why this only happens on his/her system. @portals12 Can you tell us a bit more about your setup? How did you install Syncany? Where are your JAR files located, which plugins installed?

**Comment by pimotte** [comment]
Hunch: It looks like you're on Arch. I'm guessing it's a problem with the classpath. I included a custom syncany launch for the arch PKGBUILD (as recommended by the arch people), but since we have the daemon and everything it might be a good move to switch to the syncany included one. That one does give some weird output and I'm not sure if it works. 

(The reason this happens for me with 0.4.0, but not 0.4.1 is becuase the one is installed through a PKGBUILD, and the development version is just a symlink to my build folder).

I'm currently fairly busy with non-syncany stuff, so if @portals12 would like to pick this up, that would be appreciated. (If not, I will get to it, but it might be a while.)

**Comment by binwiederhier** [comment]
It's definitely classpath-related. If a directory is found in the classpath, Guava tries to scan it completely (to look for .class files I presume).

@portals12 For debugging purposes, the output of this code snippet might be useful. I added it to the first lines of my `loadPlugins()` method:

```
System.out.println("this:            " + Thread.currentThread().getContextClassLoader());
System.out.println("parent:          " + Thread.currentThread().getContextClassLoader().getParent());
System.out.println("parent's parent: " + Thread.currentThread().getContextClassLoader().getParent().getParent());

for (URL entry : ((URLClassLoader) Thread.currentThread().getContextClassLoader().getParent()).getURLs()) {
	System.out.println("parentEntry: " + entry);
}

for (URL entry : ((URLClassLoader) Thread.currentThread().getContextClassLoader()).getURLs()) {
	System.out.println("thisEntry: " + entry);
}
```

The output of this if I call `sy plugin list` is that:

```
this:            sun.misc.Launcher$AppClassLoader@30a4effe
parent:          sun.misc.Launcher$ExtClassLoader@1c8825a5
parent's parent: null
parentEntry: file:/usr/lib/jvm/java-7-oracle/jre/lib/ext/sunjce_provider.jar
parentEntry: file:/usr/lib/jvm/java-7-oracle/jre/lib/ext/localedata.jar
parentEntry: file:/usr/lib/jvm/java-7-oracle/jre/lib/ext/sunpkcs11.jar
parentEntry: file:/usr/lib/jvm/java-7-oracle/jre/lib/ext/dnsns.jar
parentEntry: file:/usr/lib/jvm/java-7-oracle/jre/lib/ext/zipfs.jar
parentEntry: file:/usr/lib/jvm/java-7-oracle/jre/lib/ext/sunec.jar
thisEntry: file:/home/pheckel/.config/syncany/plugins/lib/syncany-plugin-gui-0.4.1-alpha+SNAPSHOT.1501061459.gitc4c4712.jar
thisEntry: file:/home/pheckel/.config/syncany/plugins/lib/syncany-plugin-webdav-0.4.0-alpha.jar
thisEntry: file:/home/pheckel/.config/syncany/plugins/lib/syncany-plugin-s3-0.4.0-alpha.jar
thisEntry: file:/home/pheckel/.config/syncany/plugins/lib/syncany-plugin-ftp-0.4.0-alpha.jar
thisEntry: file:/home/pheckel/.config/syncany/plugins/lib/syncany-plugin-sftp-0.4.1-alpha.jar
thisEntry: file:/home/pheckel/Coding/Syncany/develop/syncany/build/install/syncany/lib/bcpkix-jdk15on-1.51.jar
thisEntry: file:/home/pheckel/Coding/Syncany/develop/syncany/build/install/syncany/lib/bcprov-jdk15on-1.51.jar
thisEntry: file:/home/pheckel/Coding/Syncany/develop/syncany/build/install/syncany/lib/commons-codec-1.8.jar
thisEntry: file:/home/pheckel/Coding/Syncany/develop/syncany/build/install/syncany/lib/commons-io-2.4.jar
thisEntry: file:/home/pheckel/Coding/Syncany/develop/syncany/build/install/syncany/lib/commons-logging-1.1.3.jar
thisEntry: file:/home/pheckel/Coding/Syncany/develop/syncany/build/install/syncany/lib/guava-15.0.jar
thisEntry: file:/home/pheckel/Coding/Syncany/develop/syncany/build/install/syncany/lib/hsqldb-2.3.1.jar
thisEntry: file:/home/pheckel/Coding/Syncany/develop/syncany/build/install/syncany/lib/httpclient-4.3.4.jar
thisEntry: file:/home/pheckel/Coding/Syncany/develop/syncany/build/install/syncany/lib/httpcore-4.3.2.jar
thisEntry: file:/home/pheckel/Coding/Syncany/develop/syncany/build/install/syncany/lib/java-semver-0.7.2.jar
thisEntry: file:/home/pheckel/Coding/Syncany/develop/syncany/build/install/syncany/lib/jboss-annotations-api_1.2_spec-1.0.0.Final.jar
thisEntry: file:/home/pheckel/Coding/Syncany/develop/syncany/build/install/syncany/lib/jboss-logging-3.1.4.GA.jar
thisEntry: file:/home/pheckel/Coding/Syncany/develop/syncany/build/install/syncany/lib/jboss-servlet-api_3.1_spec-1.0.0.Final.jar
thisEntry: file:/home/pheckel/Coding/Syncany/develop/syncany/build/install/syncany/lib/jboss-websocket-api_1.1_spec-1.1.0.Final.jar
thisEntry: file:/home/pheckel/Coding/Syncany/develop/syncany/build/install/syncany/lib/jopt-simple-4.5.jar
thisEntry: file:/home/pheckel/Coding/Syncany/develop/syncany/build/install/syncany/lib/jpathwatch-0.95.jar
thisEntry: file:/home/pheckel/Coding/Syncany/develop/syncany/build/install/syncany/lib/simple-xml-2.7.1.jar
thisEntry: file:/home/pheckel/Coding/Syncany/develop/syncany/build/install/syncany/lib/stax-1.2.0.jar
thisEntry: file:/home/pheckel/Coding/Syncany/develop/syncany/build/install/syncany/lib/stax-api-1.0.1.jar
thisEntry: file:/home/pheckel/Coding/Syncany/develop/syncany/build/install/syncany/lib/syncany-cli-0.4.1-alpha+SNAPSHOT.1501061709.gitbb96309.jar
thisEntry: file:/home/pheckel/Coding/Syncany/develop/syncany/build/install/syncany/lib/syncany.jar
thisEntry: file:/home/pheckel/Coding/Syncany/develop/syncany/build/install/syncany/lib/syncany-lib-0.4.1-alpha+SNAPSHOT.1501061709.gitbb96309.jar
thisEntry: file:/home/pheckel/Coding/Syncany/develop/syncany/build/install/syncany/lib/syncany-util-0.4.1-alpha+SNAPSHOT.1501061709.gitbb96309.jar
thisEntry: file:/home/pheckel/Coding/Syncany/develop/syncany/build/install/syncany/lib/undertow-core-1.1.0.CR3.jar
thisEntry: file:/home/pheckel/Coding/Syncany/develop/syncany/build/install/syncany/lib/undertow-servlet-1.1.0.CR3.jar
thisEntry: file:/home/pheckel/Coding/Syncany/develop/syncany/build/install/syncany/lib/undertow-websockets-jsr-1.1.0.CR3.jar
thisEntry: file:/home/pheckel/Coding/Syncany/develop/syncany/build/install/syncany/lib/xnio-api-3.3.0.Beta3.jar
thisEntry: file:/home/pheckel/Coding/Syncany/develop/syncany/build/install/syncany/lib/xnio-nio-3.3.0.Beta3.jar
thisEntry: file:/home/pheckel/Coding/Syncany/develop/syncany/build/install/syncany/lib/xpp3-1.1.3.3.jar
```

**Comment by portals12** [comment]
I am using Arch and i will try help with debug when I back to home (max
1.5h).
6 sty 2015 18:14 "Philipp C. Heckel" <notifications@github.com> napisał(a):

**Comment by portals12** [comment]
I don't know exactly how but i fixed a problem. What have i done:
Removed standard Syncany package ("syncany" from aur)
Installed git version of Syncany  ("syncany-git" from aur) - still the same problem
Built Syncany with extra code in loadPlugins() method and it's started to work.
Now i don't have problem with 0.4.0-alpha and git version.

Java version:
java version "1.7.0_71"
OpenJDK Runtime Environment (IcedTea 2.5.3) (Arch Linux build 7.u71_2.5.3-3-x86_64)
OpenJDK 64-Bit Server VM (build 24.65-b04, mixed mode)
If the problem occurs again I will let you know. For now i can't reproduce it.

**Comment by pimotte** [comment]
2aed3b8a6955e9594f0bff9d63e1eef9c7531426 actually fixes this problem. (Apperently having a classpaht start with ":" means that the current directory is added.)
