### ISSUE TITLE
simple backend, but somehow it doesn't synchronize

### ISSUE THREAD

**Issue by hdijkema** [syncany/syncany#351]
I've written en simple backend, see

https://github.com/hdijkema/syncany-plugin-phprest

But somehow it doesn't synchronize files. I see temporary files created and deleted at the backend (see php subdirectory), but no real files created. 

What am I doing wrong?

**Comment by pimotte** [comment]
Great that you're exploring the plugin space:D

I suspect that the fact that not anything is done lies here: https://github.com/hdijkema/syncany-plugin-phprest/blob/master/src/main/java/org/syncany/plugins/php/PhpTransferManager.java#L134

This is the place were you would create folders. Compare to (https://github.com/syncany/syncany/blob/develop/syncany-lib/src/main/java/org/syncany/plugins/local/LocalTransferManager.java#L97).

If you use the commandline with -d (eg. `syncany init -d`, `syncany up -d`) you should be able to see where things go wrong.

**Comment by binwiederhier** [comment]
@hdijkema Looks like a good start to me. I would also suggest to add a few more log statements and then do some `sy up -d` cycles to see what's actually happening.

Can you post the output of a `sy up -d` and what you see before and after the upload on the remote backend (list of files)? That would make it easier for us to diagnose things.

**Comment by hdijkema** [comment]
I've solved the problem. Of course it was due to my programming faults.

**Comment by hdijkema** [comment]
Got the backend up and running now at grendelhosting (unlimited bandwidth, unlimited space).
http://syncany.grn.cc
