### ISSUE TITLE
Log filter mechanism; filter/include/exclude log messages by FQCN pattern (--log-include/exclude)

### ISSUE THREAD

**Issue by binwiederhier** [syncany/syncany#354]
Debugging is hard and I feel that it could be a lot easier if we were able to exclude certain log messages and/or only concentrate on certain classes.

Something like this (potential options):

```
$ sy \
   --log-include=org.syncany.gui.(history|wizard) \
   --log-include=org.syncany.daemon.gui \
   --log-include=SomeThread \
   --log-exclude=HistoryDialog \
   ...
```

Anyone up for this? This would help quite a bit!

**Comment by pimotte** [comment]
I already left this on IRC, but to leave a more permanent record: Is there anything against piping output through grep instead of building this internally?

**Comment by binwiederhier** [comment]
I feel stupid for not thinking of that myself...
