### ISSUE TITLE
Subfolder based TransferManagers

### ISSUE THREAD

**Issue by cr0** [syncany/syncany#365]
As discussed in #361 and #353 some repos require us to breakdown many files into different subfolders. Hence, I started to provide a `FolderizableTransferManager` which handles this stuff (based on @pimotte's idea).

So if a plugin wants to take advantage of this approach, its `TransferManager` has to implement [`FolderizableTransferManager`](https://github.com/syncany/syncany/blob/feature/folderizable/syncany-lib/src/main/java/org/syncany/plugins/transfer/FolderizableTransferManager.java). This [signalises Syncany to wrap](https://github.com/syncany/syncany/blob/feature/folderizable/syncany-lib/src/main/java/org/syncany/operations/AbstractTransferOperation.java#L93) the plugin's `TransferManager` in a [`FolderAwareTransferManager`](https://github.com/syncany/syncany/blob/feature/folderizable/syncany-lib/src/main/java/org/syncany/plugins/transfer/FolderAwareTransferManager.java) which handles the subfoldering stuff based on properties provided by a plugin (a plugin dev can choose if he either wants to use hard coded properties or lets a user choose them).

The `TransferManager` has to take care of the listing and cleanup stuff (like the removal of empty directories), though. I think this is too plugin specific.

You can try it using this [syncany branch](https://github.com/syncany/syncany/tree/feature/folderizable) and this [syncany-plugin-dropbox branch](https://github.com/syncany/syncany-plugin-dropbox/tree/feature/folderizable).

```
....
DropboxTransfer | main           | INFO : Dropbox: Uploading /private/tmp/11/.syncany/cache/multichunk-4384e9b561e132a54f91d78adb0b69cad03720f6 to temp file /test2/temp-temp-HhvAj-multichunk-4384e9b561e132a54f91d78adb0b69cad03720f6
DropboxTransfer | main           | INFO : Dropbox: Renaming temp file /test2/temp-temp-HhvAj-multichunk-4384e9b561e132a54f91d78adb0b69cad03720f6 to file /test2/temporary/fb/29/temp-HhvAj-multichunk-4384e9b561e132a54f91d78adb0b69cad03720f6
....
```

**Comment by binwiederhier** [comment]
Bumped to 'high' because there's a pull request waiting.
