### ISSUE TITLE
Fix ampersands (&) in menus (DefaultTrayIcon and AppIndicatorTrayIcon)

### ISSUE THREAD

**Issue by binwiederhier** [syncany/syncany#367]
Filenames with ampersands (&) are not correctly displayed in the menus. This should be an easy enough fix. Ampersands need to be escaped like this: &&

Sample fix here: 
https://github.com/syncany/syncany-plugin-gui/commit/14a76854daa26a1b95e561e1e1f00a49f7c08a9a

Possible fixes:
(a) Either fix the I18n files
or (b) fix the `setText()` instances

**Comment by cr0** [comment]
Can't find it in `AppIndicatorTrayIcon`, fixed in `DefaultTrayIcon`: https://github.com/syncany/syncany-plugin-gui/tree/hotfix/issue367

**Comment by binwiederhier** [comment]
I'll fix this in the app indicator later.

**Comment by binwiederhier** [comment]
Fixed.
