### ISSUE TITLE
Autostart on OS X does not work

### ISSUE THREAD

**Issue by cr0** [syncany/syncany#371]
Enabling Syncany autostart using the GUI does not work on OS X as files placed in `~/.config/autostart/` do not have any importance at all. 
DesktopUtil has to be extended in order to handle the OS X case, distinguishing between unixlike and windows is not enough because OS X may be based on UNIX but there are too many differences (especially in folder structure) between both OS.

However, adding an application to the autostart items of a user seems to be a bit more problematic, since it's done either manually using a OS provided GUI or automatically using a startup script. A startup script executes a specific command, though. But since the gui can be invoked by `sy gui` or launched using the standalone app we don't know which command to set in the startup script.

see: https://github.com/syncany/syncany-plugin-gui/blob/develop/src/main/java/org/syncany/gui/util/DesktopUtil.java#L110

**Comment by binwiederhier** [comment]
Interesting. As long as we make sure that it's a user-specific autostart and not something like /etc/init.d/syncany then we should be fine. I'm afraid you're the only Mac person here. So the honor is all yours.

**Comment by cr0** [comment]
Why is [`writeAutostart`](https://github.com/syncany/syncany-plugin-gui/commit/23b8afe0e5c640804fa8f8e277cf2f1817a6f980#diff-442e50d3bf6f59e71a539c2a5b9a5fd3L110) never invoked? Even dummy log messages aren't printed.

If I test it by launching the GUI and enabling autostart, I can always see that it's enabling the linux autostart. What am I missing? `EnvironmentUtil.getOperatingSystem()` should return `OSX`

**Comment by binwiederhier** [comment]
Well, what does `EnvironmentUtil.getOperatingSystem()` return? From what I can see, the preferences dialog calls the `writeAutostart()` function. And since it works for Linux, ... I don't know.

**Comment by binwiederhier** [comment]
Friendly bump.

**Comment by cr0** [comment]
Opened pr

**Comment by binwiederhier** [comment]
:+1:
