### ISSUE TITLE
Make sure tests clean up after themselves

### ISSUE THREAD

**Issue by pimotte** [syncany/syncany#377]
My /tmp is hosted in RAM, so repeatedly executing the testsuite really taxes it. I keep running into this when in the final stages of doing something else, so this is mostly a reminder issue for me to do it when not working on something else, but if someone else wants to pick this up, I'm fine with that as well.

**Comment by binwiederhier** [comment]
Just an additional comment: IMHO tests should only delete their doing if they pass. Failed tests must leave behind the files in tmp for analysis.

**Comment by cr0** [comment]
Side note: If we implement some kind of conditional junit rules (e.g. like [here](https://code.google.com/p/junit-ext/)), don't forget to add rules for OS dependent tests. If I remember it correctly such tests are failing on other OSs.

**Comment by pimotte** [comment]
@binwiederhier Is there any reason the OperationTests have their own Suite and are included in OtherShortTests?

**Comment by binwiederhier** [comment]
@pimotte Nope. I removed them.

**Comment by binwiederhier** [comment]
#386 says "Fixes #377", so I'm closing this.
