### ISSUE TITLE
The GUI crashes on Trisquel GNU/Linux

### ISSUE THREAD

**Issue by YogliB** [syncany/syncany#379]
I'm using Trisquel GNU/Linux 7.0, and the Gnome 3 desktop, and when I go into preferences in the GUI, and click on Plugins or Network, the app just crashes.

**Comment by pimotte** [comment]
Could you run the gui from the commandline (`sy gui --debug`) and provide whatever stacktrace is produced before it crashes (or the full log)?

**Comment by YogliB** [comment]
11-2-15 15:26:12.488 | MessageFactory  | XNIO-3 I/O-1   | INFO : Message created: org.syncany.operations.daemon.messages.PluginManagementResponse@538eb326
11-2-15 15:26:12.488 | InternalEventBu | XNIO-3 I/O-1   | INFO : Event bus 'GuiEventBus': Posting event PluginManagementResponse (org.syncany.operations.daemon.messages.PluginManagementResponse@538eb326) ...
11-2-15 15:26:12.507 | org.xnio.nio.se | XNIO-3 I/O-1   | TRAC : Beginning select on sun.nio.ch.EPollSelectorImpl@1ccddcc3
11-2-15 15:26:12.664 | PluginsPanel    | main           | FINE : Plugin 'dropbox' cannot be uninstalled (or updated).
**
Gtk:ERROR:/build/buildd/gtk+3.0-3.10.8/./gtk/gtkcellrenderer.c:1735:gtk_cell_renderer_get_aligned_area: assertion failed: (aligned_area->x >= cell_area->x && aligned_area->x <= cell_area->x + cell_area->width)
Aborted

**Comment by binwiederhier** [comment]
This looks like a GTK3 bug; this will very likely go away in the next release, because we're enforcing the use of GTK2. GTK3 still has some serious issues. Until all of them are resolved, we'll go back to GTK2.

We'll very likely release in the next few days. Stay tuned.

**Comment by binwiederhier** [comment]
If you try the latest snapshot of the GUI with the latest snapshot of the main application, it should work now.

**Comment by binwiederhier** [comment]
@YogliB Bump

**Comment by binwiederhier** [comment]
I assume this is fixed in the newest SNAPSHOT. If it's not, please reopen.
