### ISSUE TITLE
Box.com with WebDAV - 250 megabyte file size limit

### ISSUE THREAD

**Issue by tgharib** [syncany/syncany#380]
I'm currently using Box.com with WebDAV. However, there is 250 megabyte file size limit and I have a couple of files larger than that limit. Will syncany split up the encrypted files? Or do I have to do that?

**Comment by binwiederhier** [comment]
Syncany will split the files to max. 4MB, so no worries.

**Comment by tgharib** [comment]
Wow, quick response! Thanks!
