### ISSUE TITLE
SFTP plugin: Missing DH-SHA256 key exchange support

### ISSUE THREAD

**Issue by joelpet** [syncany/syncany#385]
The SFTP plugin is missing support for the DH-SHA256 key exchange protocol (`diffie-hellman-group-exchange-sha256`) because it's not activated in JSch.

The protocol is actually implemented in JSch, only that it's not included in it's list of capabilities causing the connection to fail, which this patch (http://sourceforge.net/p/jsch/patches/7/) fixes.

The patch was not included in the latest release of JSch (`com.jcraft:jsch:0.1.51`).

Core version: 0.4.2-alpha
SFTP plugin version: 0.4.1-alpha

**Comment by cr0** [comment]
We have to wait until this linked patch is merged and the new version is distributed via maven

**Comment by binwiederhier** [comment]
Thanks for tracking this down Joel! I wish every bug report was so detailed :)

**Comment by joelpet** [comment]
No worries! Happy to help. :) Besides, I'd really like to see compatibility with [Secure Secure Shell configuration](https://stribika.github.io/2015/01/04/secure-secure-shell.html).

**Comment by cr0** [comment]
We decided to overwrite the set of supported algorithms since a Jsch update is very unlikely.
