### ISSUE TITLE
GUI: (OSX) SFTP Create new storage requires password when private key is provided

### ISSUE THREAD

**Issue by pawi** [syncany/syncany#390]
When adding a folder with SFTP Plugin a password is required even if a password less private key for ssh is used. A single character in the password field is sufficient to proceed with the setup and get a successful sync.

Used version: Syncany v0.4.3-alpha

**Comment by pimotte** [comment]
Thanks for you bug report:)

The reason is that this password is used for an encrypted key. We should probably accept empty passwords as well.

**Comment by binwiederhier** [comment]
I knew this day would come. The problem with accepting empty passwords is that password is a mandatory field. Leaving it empty is a bit tricky :)

**Comment by pimotte** [comment]
Then maybe it should not be mandatory for sftp?

**Comment by pawi** [comment]
I think the best solution would be "it depends". It's okay that the field is required but if a private key is provided the field should be optional.

Is it possible to change the Element password to required false during validation if ```privateKey != null```?
See https://github.com/syncany/syncany-plugin-sftp/blob/139e7b5e04acc85d61d574f8eb9c7329533fc833/src/main/java/org/syncany/plugins/sftp/SftpTransferSettings.java#L114

**Comment by cr0** [comment]
We could make password optional as well and use a validator to ensure that either password, private key or both are set.

**Comment by pawi** [comment]
I would give it a try this weekend, if i can setup the toolchain to test it:

* Setting password required to False
* In validate() check if password and privateKey equals ```Null``` throw a StorageException (Either password or password less private key is required.)

**Comment by cr0** [comment]
Perfect! You can add as many validate methods to a class as you want. Only make sure that you annotate them with `@Validate` (there's no call order, though).

**Comment by binwiederhier** [comment]
@cr0 Just a reminder: When you merge something, can you make sure to update the changelog? Thanks. I did it for this issue: https://github.com/syncany/syncany/commit/f9a7e3a97467de886ab1f2933883b746dd45fcf6

**Comment by cr0** [comment]
Sure thing. sorry about that



On 8. März 2015 20:34:31 MEZ, Philipp C. Heckel <notifications@github.com> wrote:@cr0 Just a reminder: When you merge something, can you make sure to update the changelog? Thanks. I did it for this issue: f9a7e3a   —Reply to this email directly or view it on GitHub.
