### ISSUE TITLE
hubiC plugin (swift solution but with OAuth2)

### ISSUE THREAD

**Issue by homlett** [syncany/syncany#402]
Hi,

It would be nice to have a hubiC plugin. hubiC is a cloud storage service by OVH. It's very cheap.
https://hubic.com/en/offers/

hubiC is a swift solution but with its own auth method. Details available here :
https://api.hubic.com/sandbox/

So, the _syncany-plugin-swift_ is probably a good base :
https://github.com/syncany/syncany-plugin-swift

Moreover, the FOSS _Swift Explorer_ is hubiC compatible now. So, it's maybe a good ressource too. See :
http://www.swiftexplorer.org
https://github.com/roikku/swift-explorer

Thanks for Syncany !

Regards,

**Comment by binwiederhier** [comment]
Hi @homlett and awesome that you're interested in Syncany. I've never heard of HubiC before and without looking into it in detail, it looks like another storage provider to me.

If you have programming skills, we encourage you to either develop your own HubiC plugin and you can soon publish it as a 3rd party plugin -- or you can give specific instructions what to do to extend the Swift plugin accordingly. 

Given that we're currently a *very* small team, it is very unlikely that we'll be able to implement and test an entirely new plugin.

**Comment by homlett** [comment]
Alright, I perfectly understand!
Unfortunatly, I'm not able to code that myself, but maybe someone else...

Regards,

**Comment by binwiederhier** [comment]
Third party plugins can now be published to the Syncany server. If you find someone to implement this, let us know and we'll help out.

**Comment by cortopy** [comment]
@homlett while a plugin would be great, you don't really need it. I've just been trying syncanny out and it's too good to miss out

If you use hubic, you can just use [hubicfuse](https://github.com/TurboGit/hubicfuse) to mount locally. And then, just use the local syncanny plugin as explained in the [docs](https://github.com/syncany/syncany/wiki/CLI-full-example)

That's what I've just set up and it works perfectly

**Comment by fbardel** [comment]
+1 by a Hubic plugin : [Hubic API](https://api.hubic.com/)
