### ISSUE TITLE
Build fails for plugins because of SonarRunner

### ISSUE THREAD

**Issue by cr0** [syncany/syncany#403]
As one can see in [that buildlog](https://travis-ci.org/syncany/syncany-plugin-dropbox/builds/53163161), all plugin builds are failing because of SonarRunner.

```
FAILURE: Build failed with an exception.
* Where:
Script '/home/travis/build/syncany/syncany-plugin-dropbox/core/gradle/gradle/reports.sonarqube.gradle' line: 8
* What went wrong:
A problem occurred evaluating script.
> Failed to apply plugin [id 'sonar-runner']
   > Cannot add extension with name 'sonarRunner', as there is an extension already registered with that name.
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```

see syncany/syncany-plugin-dropbox#3

**Comment by MrHug** [comment]
I will work on this soon, you may assign if you want :wink:

**Comment by cr0** [comment]
Unfortunately, Github does not allow to assign non collabs to issues :(

**Comment by MrHug** [comment]
Ah ok, well I'll look at it regardless :)

Op zo 8 mrt. 2015 om 15:45 schreef Christian Roth <notifications@github.com

**Comment by cr0** [comment]
Good to hear, thanks.
