### ISSUE TITLE
Chunking not working correctly

### ISSUE THREAD

**Issue by thebasicwizard** [syncany/syncany#404]
**Set-Up**
I have folder containing a 600MB ISO and a few small text files. On my SFTP server, the multichunks created are approx: 157 in totoal and range frrom 2-4MB in size. I later added a 5MB image file which created an additional 2 multi-chunks of 3MB and 1MB. All my clients are fully synced and have a copy of all the files (ISO, text files and the 5MB image).

*Note: I'm using Windows 7, Java (1.8.0_31), SFTP plugin and I'm using the GUI not the command-line*

**Problem**
The actual syncing works fine but it's the size of the muti-chunks which is the problem. Everytime I change 1 pixel in the 5MB image file, 2 new multi-chunks are created (3MB and 1MB). The clients download 2 new, overly large chunks, everytime I change 1pixel.

I understand that there should be a 512k chunk size not 5MB and changing 1 pixel should result in a multichunk download of a max. size of 512KB. It seems to be download the while file, rather than a small segment (of 512KB).

**Comment by binwiederhier** [comment]
What kind of image file is it? JPG re-encodes the entire file whenever you save it -- meaning that you lose image quality with every save. PNG actually gzips the raw image RGB data (and stores them in so called IDAT chunks), which unfortunately also might change completely if you change a few pixels of the image. The deduplicate-able image format I know is BMP -- which nobody ever uses. 

That's actually one of the reasons why we have so large chunks -- there are only a few file formats out there that benefit from dedup...

**Comment by thebasicwizard** [comment]
DOH! I never thought of that.  I'm using PNG format so the image could well
be 100% different when saved. I havn't done a file-diff yet to confirm but
it makes perfect sense now you've explained it :) I'll check and let you
know ASAP.

I will also look at BMP files just as an extra test.

Cheers.

**Comment by binwiederhier** [comment]
I'm pretty sure you can turn of PNG compression. Then Syncany's dedup will work, and since we also compress, it won't matter in terms of size. I'm closing this issue; please re-open if it doesn't work out with BMPs.
