### ISSUE TITLE
webdav plugin: cannot initialize repository

### ISSUE THREAD

**Issue by elephaant** [syncany/syncany#406]
Syncany fails to initialize new webdav repository claiming target cannot be created.

syncany version 0.4.3
webdav plugin: 0.4.0

wa@clef:~/edav$ sy init -t
Choose a storage plugin. Available plugins are: local, sftp, webdav
Plugin: webdav

Connection details for webdav connection:
- URL: https://edav.ssss.com:5006/home
- Username: edav
- Password (not displayed): 

ERROR: Repository cannot be initialized, because the target does not exist and
       it cannot be created. Please check your permissions or create the target manually.

Details:
- Target connect success: true
- Target exists:          false
- Target creatable:       false
- Target writable:        false
- Repo file exists:       false

Connection failure
Would you change the settings and retry the connection (y/n)? n

## However cadaver has no problems writing to it

wa@clef:~/edav$ cadaver https://edav.ssss.com:5006/home
WARNING: Untrusted server certificate presented for `synology.com':
Certificate was issued to hostname `synology.com' rather than `edav.ssss.com'
This connection could have been intercepted.
Issued to: FTP Team, Synology Inc., Taipei, Taiwan, TW
Issued by: Certificate Authority, Synology Inc., Taipei, Taiwan, TW
Certificate is valid from Sat, 17 Jan 2015 18:55:19 GMT to Wed, 04 Oct 2034 18:55:19 GMT
Do you wish to accept the certificate? (y/n) y
Authentication required for SYNO_WebDAV Storage on server `edav.ssss.com':
Username: edav
Password: 
dav:/home/> ls
Listing collection `/home/': collection is empty.
dav:/home/> mkcol somedir
Creating `somedir': succeeded.
dav:/home/> ls
Listing collection `/home/': succeeded.
Coll:   somedir                                0  Mar  9 19:36
dav:/home/> rmcol somedir
Deleting collection `somedir': succeeded.
dav:/home/> quit
Connection to `edav.ssss.com' closed.

## Syncany logs reveal execptions thrown:

9-3-15 19:34:52.410 | AbstractInitOpe | main           | INFO : Running 'Init'
9-3-15 19:34:52.410 | AbstractInitOpe | main           | INFO : --------------------------------------------
9-3-15 19:34:52.430 | AbstractTransfe | main           | INFO : Performing storage test TM.test() ...
9-3-15 19:34:52.431 | AbstractTransfe | main           | INFO : - Running connect() ...
9-3-15 19:34:52.431 | WebdavTransferM | main           | INFO : WebDAV: Connect called. Creating Sardine (SSL!) ...
9-3-15 19:34:53.511 | WebdavTransferM | main           | WARN : testTargetExists: Exception thrown while testing if folder exists.
javax.net.ssl.SSLProtocolException: handshake alert:  unrecognized_name
        at sun.security.ssl.ClientHandshaker.handshakeAlert(ClientHandshaker.java:1373)
        at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:1952)
[...]
9-3-15 19:34:53.540 | WebdavTransferM | main           | INFO : testTargetCanWrite: Can NOT write to target.
javax.net.ssl.SSLProtocolException: handshake alert:  unrecognized_name
        at sun.security.ssl.ClientHandshaker.handshakeAlert(ClientHandshaker.java:1373)
        at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:1952)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1077)
[...]
9-3-15 19:34:53.569 | WebdavTransferM | main           | WARN : testRepoFileExists: Exception thrown while testing if repo file exists.
javax.net.ssl.SSLProtocolException: handshake alert:  unrecognized_name
        at sun.security.ssl.ClientHandshaker.handshakeAlert(ClientHandshaker.java:1373)
[...]

**Comment by binwiederhier** [comment]
The TLS SNI extension on the server seems to send the wrong hostname, or you are connecting to the wrong hostname. Can you check if this is the exact hostname that the provider suggests? Or try other hostnames?

According to [this post](http://stackoverflow.com/a/1488494), most other clients/libraries ignore this issue, but Java does not. I tend to agree with the JDK devs on this one that this is not a client issue, but a misconfigured server issue. However, the [proposed workaround](https://github.com/Lekensteyn/OWASP-WebScarab/commit/8f2362eb021924cece9fb544f04bde5da7bfed4a) seems reasonable. I'm not sure whether we can implement it though, or if our WebDAV library Sardine will have to do that.

**Comment by elephaant** [comment]
Is it really oracle jdk issue as suggested by Lekensteyn?  I could try icedt, or java8 but if it 'solves' by ignoring SNI then it does not advance the issue.  I think jdk may be correct in raising an exception and leaving it up to the user, in this case Sardine, to handle it.

**Comment by binwiederhier** [comment]
Would it be okay if I close this? I think this is clearly a misconfigured server issue, not a Syncany issue.

**Comment by elephaant** [comment]
Yes, you can close it.

I think there is a user friendliness issue which is why most browsers and cadaver allow for this type of 'misconfiguration' but I don't think syncany should be fixing it.  It should probably be fixed in the library used for webdav access.
