### ISSUE TITLE
Decryption/extraction of multichunk failed

### ISSUE THREAD

**Issue by binwiederhier** [syncany/syncany#408]
@Asherehsa raised this issue in https://github.com/syncany/syncany/issues/59#issuecomment-78428175 -- I feel that this deserves its own issue:

"I'm using Syncany on 4 different computers and one is coming up with the error you posted (the others seem to be working fine): Error: Downloading multichunk 4/268 ...Error: Decryption/extraction of multichunk c425608908e42d2d15d87377cb2070088764d505 failed. The multichunk might have been tampered with!
I'm sorry if this is the wrong place for feedback but are there any tips for resolving the error? "

**Comment by binwiederhier** [comment]
This is a very, very bad sign! 

Please try the following things **in this order**:

(a) Can you provide a detailed log when you run `sy down --debug`. The output will be printed on the console and will also have more detail in the log file (.syncany/log/syncany.log; **not** the daemon log file in .config/syncany/log/syncany.log)

(b) Can you empty the cache of the failing client and see if that solves the problem? Just delete everything in `.syncany/cache/*`.

(c) Can you reconnect the failing client by deleting/moving `.syncany` and doing `sy connect`, and see if that solves the problem?

If neither of this works, that means you multichunk is corrupt. Which should never happen. In that case, can you answer the following questions:

(d) What plugin are you using?

(e) Is it possible that someone tampered with the multichunk?

(f) If you download the multichunk manually and put it inside your local sync folder (turn of the daemon first), you can try to manually decrypt it via `sy --d debug decrypt multichunk-* > multichunk-decrypted.zip`. Does that work?

**Comment by Asherehsa** [comment]
Thank you for creating this!
a. sy down --debug seems to have fixed it...or maybe restarting the computer did. Running the debug command preformed a successful sync! Anyway here is the log, I tried to edit out the file names
https://gist.github.com/Asherehsa/554d26c65a45da78997e

d. I'm using the local plugin to sync with the box.com client and not using the daemon.
