### ISSUE TITLE
Update notification for Syncany

### ISSUE THREAD

**Issue by binwiederhier** [syncany/syncany#412]
It'd be very nice if Syncany would check for a new version every day or so.
I just finished the API call for that; it should be easy enough:

https://api.syncany.org/v3/app
https://api.syncany.org/v3/app?snapshots=true

**Comment by cr0** [comment]
Is there any reason why the Mac Version isn't listed?

**Comment by binwiederhier** [comment]
The non-CLI versions are uploaded through the "PUT /plugins" API and not through "PUT /app", but you are right, they should show up here. I'll integrate them in the next few days. We might need to change the resulting XML for that, because they will likely have different timestamps/build data.

**Comment by binwiederhier** [comment]
This should work now -- all we have to do is implement the Syncany client part of it. Here are a few sample requests -- all the 0.4.3-alpha results are added to the database manually, everything else via Travis/API upload:

Releases (manually added):
https://api.syncany.org/v3/app
https://api.syncany.org/v3/app/gui
https://api.syncany.org/v3/app/gui?type=exe&arch=x86_64
https://api.syncany.org/v3/app/gui?type=app.zip&arch=x86_64
https://api.syncany.org/v3/app/cli
https://api.syncany.org/v3/app/cli?type=zip
https://api.syncany.org/v3/app/cli?type=zip&os=windows&arch=x86 (same result!)

Snapshots:
https://api.syncany.org/v3/app/cli?snapshots=true&os=linux&type=deb
https://api.syncany.org/v3/app/cli?snapshots=true&os=macosx
https://api.syncany.org/v3/app/gui?snapshots=true&os=macosx&type=app.zip
....

**Comment by binwiederhier** [comment]
This is the Java side for the update checks:
https://github.com/syncany/syncany/compare/feature/issue412-sy-update

```bash
$ sy update check
Up to date. At version 0.4.4-alpha+SNAPSHOT.1503221305.gitce8578b.
```

```bash
$ sydev update check
A new version is available. Local version is 0.4.4-alpha, remote version is 0.4.5-alpha.
Download at https://get.syncany.org/dist/releases/syncany_0.4.5.alpha_all.deb
```

Questions:
(a) Any suggestions? Objections to merge this?
(b) My plan would be to add a daily check to perform that by the GUI. 
(c) I am not sure whether it's a good idea to also perform an update check in the `CommandLineClient` every day or so and outputting it *before* any other command is called. An example output might look like this: 

```bash
$ sy status
Daily update check: 
  A new version is available. Local version is 0.4.4-alpha, remote version is 0.4.5-alpha.
  Download at https://get.syncany.org/dist/releases/syncany_0.4.5.alpha_all.deb

No local changes.
```

If the update check output is written to STDERR it shouldn't destroy scriptability, but I'm still unsure if it's a good idea. Thoughts?

**Comment by pimotte** [comment]
(a) Did a dry-review. LGTM
(b) Sounds good.
(c) Nooooooooooooooo *fades as if Pim is falling from a cliff*

The update check is already exposed through the CLI. I see no reason to force feed this CLI users, of whom 97.8% will have installed through distro repo/ppa/aur anyway. (Percentage pulled of of thin air.)

**Comment by binwiederhier** [comment]
Haha. Ok then. Pim has spoken :smile:

**Comment by binwiederhier** [comment]
GUI stuff in #415. Hereby closed.
