### ISSUE TITLE
Gui wont launch

### ISSUE THREAD

**Issue by alkaphreak** [syncany/syncany#413]
Maybe related to issues already on Github about the gui not launching correctly.

When i start my session, the gui isn't launching, it was launching fine when i first installed syncany.

When i try in term :
```
freak0@alkaBook:~/Syncany/SyTest$ sy gui
- XNIO version 3.3.0.Beta3
- XNIO NIO Implementation Version 3.3.0.Beta3
```

And that's all, no more. The gui isn't popping in my tray or wherever.

The daemon seem launched at the start of the session.

I don't know what to provide (logs...) to add some precision.

System : Linux / Ubunut 14.10

**Comment by cr0** [comment]
Hi, please provide the debug output using `sy gui -d`.

**Comment by alkaphreak** [comment]
So with the command :
```
sy gui -d > ~/sy-gui-d.txt 2>&1D
```
I'm sending this to you by mail.

**Comment by binwiederhier** [comment]
Are you on Ubuntu Unity? If yes, try `sy gui --tray=APPINDICATOR`. You can make this permanent by editing the gui.xml file in the ~/.config/syncany folder. 

If it doesn't work: Which OS and desktop environment are you on?

**Comment by alkaphreak** [comment]
Like said before i'm on Ubuntu
```
System : Linux / Ubunut 14.10
```
And yes with Unity.

I've tried :
```
sy gui --tray=APPINDICATOR
```
It works.

So i've made 
```
$cp ~/.config/syncany/gui-example.xml ~/.config/syncany/gui.xml
```
Then a session reboot, no gui in tray. I'm trying it with the dash, nothing.

I think, something is missing in my xml file.

```xml
<gui>
   <tray>DEFAULT</tray>
   <theme>DEFAULT</theme>
   <startup>true</startup>
   <notifications>true</notifications>
</gui>
```
I have seen nothing in the docs about this.

**Comment by cr0** [comment]
`<tray>DEFAULT</tray>` should be `<tray> APPINDICATOR </tray>`

@binwiederhier Why is this not automatically set by the GUI?

**Comment by alkaphreak** [comment]
Ok, with the ```<tray>APPINDICATOR</tray>``` it pop in the tray and seem to synch (green icon) when i start it from the dash. 

I did a reboot and nothing in the tray, starting it from the dash and no green or blue icon on the sy gui icon in the tray.

Something went wrong. Maybe the daemon isn't launched. Trying in debug with the sy gui still active.
```
sy daemon start -d > ~/sy-daemon-d.txt 2>&1

Starting daemon: .......... Failed to start process. EXITING.
Failed command line: $  daemon run
```
Trying again with the gui closed. Same result.

/me sad

**Comment by binwiederhier** [comment]
@cr0 It should, that's why I'm trying to determine the desktop environment. :)

@alkaphreak 

(a) Sorry for missing the remarks about you being on Ubuntu. Can you tell me what desktop environment you're on? Unity, Cinnamon, XFCE, KDE? If you're running vanilla Ubuntu from the Ubuntu website, you're probably running Unity and the GUI should've detected that...

(b) Sorry you're having such difficulties with it. The 'APPINDICATOR' tray has it's issues -- it's written in Python and crashes sometimes while the main application continues to run in the background. That's probably what's happened with you. If you do `sy daemon force-stop`, it'll stop the daemon.

(c) If you want to debug the daemon, you can do: `sy daemon run -d` (not start!)

(d) If the daemon is not running and you want to run the GUI, it'll run the daemon for you; you can debug that via `sy gui -d`.

(e) If the daemon *is* running and you run the GUI, you'll only see half of the output because the GUI will connect to the running daemon. I would not suggest running them separately.

**Comment by binwiederhier** [comment]
(f) The GUI stuff should be in the docs, but it isn't ... I've added a new issue for that #414

**Comment by alkaphreak** [comment]
(a) Ubuntu Unity yeah :)

(b) So i did : 
```
freak0@alkaBook:~$ sy daemon force-stop
Force-stopping daemon: syncanyd not running
```

(c) Then i did : 
```
sy daemon run -d > ~/sy-daemon-d.txt 2>&1
```
And got : 
```
debug
Application version: 0.4.3-alpha
18-3-15 12:58:05.320 | CommandLineClie | main           | INFO : Application version: 0.4.3-alpha
18-3-15 12:58:05.432 | PidFileUtil     | main           | INFO : isProcessRunningUnixLike(3470) returned 0, process running = true
18-3-15 12:58:05.436 | DaemonOperation | main           | INFO : Starting daemon operation with action RUN ...
18-3-15 12:58:05.440 | PidFileUtil     | main           | INFO : isProcessRunningUnixLike(3470) returned 0, process running = true
18-3-15 12:58:05.440 | CommandLineClie | main           | SEVE : Command org.syncany.cli.DaemonCommand@13c78c0b FAILED. 
org.syncany.operations.daemon.ServiceAlreadyStartedException: Syncany daemon already running.
	at org.syncany.operations.daemon.DaemonOperation.executeRun(DaemonOperation.java:197)
	at org.syncany.operations.daemon.DaemonOperation.execute(DaemonOperation.java:113)
	at org.syncany.cli.DaemonCommand.execute(DaemonCommand.java:50)
	at org.syncany.cli.CommandLineClient.runLocally(CommandLineClient.java:389)
	at org.syncany.cli.CommandLineClient.runCommand(CommandLineClient.java:379)
	at org.syncany.cli.CommandLineClient.start(CommandLineClient.java:195)
	at org.syncany.Syncany.main(Syncany.java:55)
Error: Syncany daemon already running.
       Refer to help page using '--help'.
```
So it said that it's not running then that it was running ... grrr.

**Comment by binwiederhier** [comment]
Can you do `ps aux | grep 3470` (3470 being the PID).

**Comment by alkaphreak** [comment]
freak0@alkaBook:~$ ps aux | grep 3470
freak0   11990  0.0  0.0  13732  2212 pts/10   S+   13:21   0:00 grep --color=auto 3470

**Comment by binwiederhier** [comment]
Interesting and really odd. Seems like the PidFileUtil is not working correctly. For now, just delete the daemon PID and control file if you are sure that it is not running: `rm ~/.config/syncany/daemon.{pid,ctrl}`.

**Comment by alkaphreak** [comment]
I did a reboot for something else and tada, sy gui lanched, green icon, i did just a little trick that may nothing to have with my problem.

With 'menulibre' (https://launchpad.net/menulibre) i've modfied the syncany gui entry from : 
```
sy gui
```
To : 
```
sy gui --tray=APPINDICATOR
```

**Comment by binwiederhier** [comment]
@alkaphreak You shouldn't have to do that. The setting in the `gui.xml` will do that for you. If it is set, you don't need the `--tray=APPINDICATOR`.

**Comment by alkaphreak** [comment]
That's what i was thinking too :)

**Comment by binwiederhier** [comment]
(1) But it doesn't work? Or why did you have to add `--tray=APPINDICATOR`?

(2) Would you mind running the following two commands for me and posting the output?

```bash
ps --no-headers -C unity-panel-service
echo $XDG_CURRENT_DESKTOP
```

**Comment by alkaphreak** [comment]
(1) I did'nt know if it was working with or without '--tray=***' in the dash menu, i've add it, reboot for something else and, it worked.

I will try to remove it and then reboot again for curiosity.

(2) Here it is : 
```
freak0@alkaBook:~$ ps --no-headers -C unity-panel-service
 2128 ?        00:00:50 unity-panel-ser
freak0@alkaBook:~$ echo $XDG_CURRENT_DESKTOP
Unity
freak0@alkaBook:~$ 
```

**Comment by alkaphreak** [comment]
(1) it worked gui and daemon launched without  '--tray=***' in the dash menu.

**Comment by binwiederhier** [comment]
It's still odd that the GUI doesn't detect that you're on Unity. It runs `ps --no-headers -C unity-panel-service` and assumes that you're on Unity if the output is non-empty...

**Comment by alkaphreak** [comment]
I will close the issue, unless you wanna add something ?

**Comment by binwiederhier** [comment]
Go wild :+1:

**Comment by binwiederhier** [comment]
@alkaphreak Apparently there was something wrong here: https://github.com/syncany/syncany-plugin-gui/commit/9ca02b7d3de768f84000c35e606b5ee3a9fe832a -- thanks again for pointing it out!

**Comment by alkaphreak** [comment]
You're welcome.

Maybe i will clone the projet to give a hand at improving the development a bit :)

If i can find some free time.
