### ISSUE TITLE
Plugin update on Windows ignores snapshot flag

### ISSUE THREAD

**Issue by cr0** [syncany/syncany#418]
Plugin update on Windows ignores snapshot flag because of the update file workaround. Extending the plugin identifier with `-s` ([here](https://github.com/syncany/syncany/blob/develop/syncany-lib/src/main/java/org/syncany/operations/plugin/PluginOperation.java#L173)) and write it to the update file should solve this issue.

Found out here #417

**Comment by binwiederhier** [comment]
Sounds like a plan :+1:
