### ISSUE TITLE
Google Cloud Storage support

### ISSUE THREAD

**Issue by bobobo1618** [syncany/syncany#427]
With GCS beating S3 pricing and features, it'd be great if you could add Google Cloud storage support to the S3 plugin. From what I saw Jets3t already has support for it and the APIs are pretty much identical to S3.

I'd be interested in adding it myself but I have to ensure it's permitted by my employer prior to doing so.

**Comment by bobobo1618** [comment]
Okay, I appear to have implemented it, just waiting on approval to submit the pull request.

**Comment by esafwan** [comment]
@bobobo1618 Have you hosted the code anywhere online?

**Comment by bobobo1618** [comment]
@esafwan my PR is referenced earlier in this thread. As you seem to have discovered, cr0 and binwiederhier implemented and committed their own (superior) implementation in https://github.com/syncany/syncany-plugin-s3/pull/5
