### ISSUE TITLE
The system cannot find the file C:\Documents

### ISSUE THREAD

**Issue by moonbug** [syncany/syncany#434]
I ran sy -vfrom Windows command prompt and get
The system cannot find the file C:\Documents.
I believe this is due to the spacing in C:\Documents and Settings\username
What should I adjust to correct this?

**Comment by pimotte** [comment]
Thanks for reporting this. 

Is "The system cannot find file C:\Documents" the complete and exact error message?

**Comment by binwiederhier** [comment]
@moonbug 
I cannot confirm that running `sy -v` from `C:\Documents and Settings` throws an error. Can you show the complete command and error message?

Random thought: `C:\Documents and Settings\username` doesn't even exist anymore on my Windows, because the user data is actually in `C:\Users\username` now. Maybe that's it ...

**Comment by Asherehsa** [comment]
@moonbug What is current working directory ("cd" command) when you run this command?

**Comment by binwiederhier** [comment]
This was 23 days ago an we haven't heard from you @moonbug. I'm closing this because I could not confirm the issue. Please let us know if this happens again.

**Comment by Triquetra** [comment]
I can confirm this bug.  Running "sy" from "C:\Documents and Settings\User" produces "The system cannot find file C:\Documents".  Yes, that is the complete and exact error message.  Note that I initially ran sy in that directory, now that error is thrown regardless of the current working directory.

**Comment by moonbug** [comment]
It seems to work regardless of the  sy -v error

**Comment by Triquetra** [comment]
Every syncany command produces this error for me, though, for the moment at least, it does seem to function regardless of the error.

**Comment by Triquetra** [comment]
OK, now I'm running into problems that may, or may not, be related.  I'm trying to initialize a new repository (sy init).  The first line after running "sy init" is "The system cannot find file C:\Documents"

The command seems to complete, but then after creating the master key from the password, I get "Error: couldn't upload to remote repo. Cleaned local repository."

A subsequent "sy status" says no repository found in path.

**Comment by moonbug** [comment]
activate and use the GUI interface instead of the command line ( in the lower right corner).

**Comment by Triquetra** [comment]
Thank you.  I tried using the gui, but it produced the following error:

Unable to initialize folder (Code: 501)
The operation failed entirely.  An exception was thrown.

**Comment by moonbug** [comment]
What OS are you using?
Got JAVA installed?
Are you syncing to dropbox or local network folder?
When does error occur? Add folder>Create new online storage>
I've tested it with dropbox and shared local folder only

**Comment by Triquetra** [comment]
Windows XP SP3
Yes, Java is installed.
Syncing to Amazon S3
The error occurs after add folder>create new online storage>set password>initializing remote repository>Error

**Comment by moonbug** [comment]
Test it with dropbox first. If it works then it is an issue with the Amazon S3 syncany plugin

**Comment by Triquetra** [comment]
I installed the dropbox plugin, but when I try to get an authentication token, I get the following error from dropbox:"This app is in development mode and can't accept more users. Contact the app developer and ask them to use the Dropbox API App Console to apply for production status."

**Comment by moonbug** [comment]
try going back after the error  and choose add an existing syncany folder. See if that syncs to your S3

**Comment by Triquetra** [comment]
I tried "connect to an existing repository" after receiving the above described error on attempting to initialize a new repository.  Immediately upon selecting "connect to an existing repository" the syncany application crashes and closes.

**Comment by moonbug** [comment]
There might be an issue with the new dropbox plugin. I cannot test S3 because I have no account.
But I am getting the same error you have with the new version of Syncany (v4.5 and v4.6) and dropbox plugin.

**Comment by Triquetra** [comment]
Hmm ... so this is probably not related to the "The system cannot find file C:\Documents" error.  Should we open a new ticket?

**Comment by moonbug** [comment]
I have open a new ticket for dropbox plugin under https://github.com/syncany/syncany/issues/521
and another user with similar issue
https://github.com/syncany/syncany/issues/518
