### ISSUE TITLE
sy daemon start may error

### ISSUE THREAD

**Issue by Kudret** [syncany/syncany#439]
rerunning immediately after did not error, though.

kudret@fin:~/Desktop$ sy daemon status
Checking daemon: syncanyd not running
kudret@fin:~/Desktop$ sy daemon start
Starting daemon: ./usr/bin/sy: line 225: [: -eq: unary operator expected
error: process ID list syntax error

Usage:
 ps [options]

 Try 'ps --help <simple|list|output|threads|misc|all>'
  or 'ps --help <s|l|o|t|m|a>'
 for additional help text.

For more details see ps(1).
.. syncanyd (pid 3414).
kudret@fin:~/Desktop$ sy daemon status
Checking daemon: syncanyd running (pid 3414).
kudret@fin:~/Desktop$ sy daemon stop 
Stopping daemon: ... syncanyd stopped.
kudret@fin:~/Desktop$ sy daemon start
Starting daemon: .. syncanyd (pid 3661).
kudret@fin:~/Desktop$

**Comment by binwiederhier** [comment]
@Kudret You find the strangest errors :+1: Thanks for reporting. https://github.com/syncany/syncany/commit/c48ad36b201b78fd3ec4d152dc3472ebfbfe5192 should deal with this. 

Cause is that you daemon pid file was empty. Any idea how that happened?

**Comment by Kudret** [comment]
It happened to me multiple times and on multiple systems. I start the daemon with sy daemon start but never stop it before turning a system off. Would that cause this?
