### ISSUE TITLE
OAuth Dropbox GUI doesn't work

### ISSUE THREAD

**Issue by binwiederhier** [syncany/syncany#441]
Reminder issue

**Comment by cr0** [comment]
This is because of the new OAuth listener, right? I started with this issue here: https://github.com/syncany/syncany-plugin-gui/tree/feature/oauth-callback
However, some changes in the `DaemonConfigHelper` were a showstopper since I don't know who did them and how to circumvent them.

**Comment by cr0** [comment]
@binwiederhier: You removed the code in this [commit](https://github.com/syncany/syncany/commit/29f2534a90b32253d23539c608de2e8aadb58715) with a comment that it is unused. Should I revert this change or move that method to the gui lib?

**Comment by binwiederhier** [comment]
Oops. Just re-add the required functions. Good catch :+1:
