### ISSUE TITLE
Add license to all projects within Syncany

### ISSUE THREAD

**Issue by cr0** [syncany/syncany#445]
All repositories except the main repo are missing license files. We should add them to prevent some misunderstandings.

- [X] syncany
- [ ] gui
- [ ] assets 
- [ ] docs
- [ ] website
- [ ] storage plugins
 - [ ] dropbox
 - [ ] s3
 - [ ] sftp
 - [ ] webdav
 - [ ] swift
 - [ ] samba
 - [ ] raid0
 - [ ] simpleweb
- [ ] bot
- [ ] osx-notifier

According to Github's FAQs, all projects without a license are
> Generally speaking, the absence of a license means that the default copyright laws apply. This means that you retain all rights to your source code and that nobody else may reproduce, distribute, or create derivative works from your work. This might not be what you intend.
> https://help.github.com/articles/open-source-licensing/

The last sentence really is a point!

**Comment by binwiederhier** [comment]
Done
