### ISSUE TITLE
Copy.com support

### ISSUE THREAD

**Issue by cemsbr** [syncany/syncany#447]
Please, add a plugin for copy.com - https://developers.copy.com/documentation

**Comment by pimotte** [comment]
Plugin requests, especially for targets which don't have a Java SDK/library, are pretty low priority right now. We might have time for things like these in the future.

If you want to give it a shot yourself, feel free to contact us if you run into any problems on the Syncany side.

**Comment by cr0** [comment]
I've created a separate wiki page which [lists all plugin requests](wiki/Plugin-Overview).

**Comment by ferdnyc** [comment]
Barracuda have announced that [they're EOL'ing the Copy service](https://blog.barracuda.com/2016/02/01/message-from-gm-of-storage/), which will shut down on May 1, 2016. So, this is probably a moot point now.

**Comment by cemsbr** [comment]
Thanks for the warning. I'm sad to hear that. I had a free 72-GB account... As people will be moving from Copy.com, I'm closing this issue.
