### ISSUE TITLE
Problem installing on Mac OSX 10.10.3 (Yosemite)

### ISSUE THREAD

**Issue by mlmedia** [syncany/syncany#449]
Hello and thanks for creating this tool.  I'm having a problem installing on Mac OSX Yosemite following the instructions.  It gives the error that Java 1.7 is required but the version is 1.8.

Commands below with errors (for the search engines):

Macs-Mac-mini:~ macowner$ brew install https://get.syncany.org/homebrew/syncany.rb
######################################################################## 100.0%
syncany: Java 1.7 is required to install this formula.
You can install with Homebrew Cask:
  brew install Caskroom/cask/java

You can download from:
  http://www.oracle.com/technetwork/java/javase/downloads/index.html
Error: An unsatisfied requirement failed this build.
Macs-Mac-mini:~ macowner$ java -version
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)
Macs-Mac-mini:~ macowner$ brew install Caskroom/cask/java
==> brew cask install Caskroom/cask/java
Warning: A Cask for java is already installed. Add the "--force" option to force re-install.
Macs-Mac-mini:~ macowner$

**Comment by mlmedia** [comment]
I installed using the app.zip and the GUI tool seems to be working, however command line is not.  So I believe I will be able to use it, but this way still be worth exploring for you guys.

Macs-Mac-mini:~ macowner$ sy plugin list
-bash: sy: command not found
Macs-Mac-mini:~ macowner$

**Comment by cr0** [comment]
Yep, the GUI version (the precompiled app.zip) does not include the commandline interface. At the moment, there is no intention to change that.

**Comment by binwiederhier** [comment]
We don't ship the CLI with the GUI? Isn't that just a matter of adding the PATH correctly?

**Comment by cr0** [comment]
We could put the bash script in the app bundle and adjust classpath stuff. However, I consider that ultra low priority because we also have the homebrew script which provides the CLI.

**Comment by mlanner** [comment]
@cr0 While I realize this has been closed, I agree with @binwiederhier that it would be very handy to have the CLI available through the app. I was a) trying to troubleshoot the installation (had a really old version of Syncany previously installed) and b) I wanted to list the plugins (just like @mlmedia). Seems like also having the CLI would be handy and allow me to script things if I wanted to.
