### ISSUE TITLE
Change settings to get over "No enum constant org.syncany.plugins.s3.Location.us-west-1"

### ISSUE THREAD

**Issue by jgn** [syncany/syncany#471]
I think the new alpha has some kind of translation table for the S3 plugin so that you indicate region with "US-WEST" but older versions want to leverage the constant "constant org.syncany.plugins.s3.Location.us-west-1" --

Can I hand-edit a file to get over this?

**Comment by cr0** [comment]
Thanks for reporting, we totally missed that compatibility break.

You can edit the `syncany/config.xml` in the synced directory. Replace `location` with `US_WEST`. I think that should solve the issue.

**Comment by binwiederhier** [comment]
**Did you upgrade to the latest S3 plugin? Because it has ENUM constants ....** Too late...

**Comment by binwiederhier** [comment]
@cr0 was faster...

**Comment by jgn** [comment]
I'm on 0.4.5 alpha, and for the plugin I have the newest snapshot (`sy plugin install s3 --snapshot`).

I'll reinstall the plugin, though.

**Comment by binwiederhier** [comment]
Follow Christians instructions and you should be fine.

**Comment by jgn** [comment]
Will do.
