### ISSUE TITLE
Installers/GUI/CLI give no indication of what is wrong when Java is not installed.

### ISSUE THREAD

**Issue by pimotte** [syncany/syncany#478]
This is relevant for all OS's where the gui is launched without use of a command line. At least Windows, probably Mac too?

The launcher should probably give a pop-up indicating the user needs to install Java.

**Comment by cr0** [comment]
Gradle macappbundle, which we use, is actually generating an appropriate error measage.

**Comment by pimotte** [comment]
Including #526. The mac (CLI) homebrew version apperently does not enough pre-checking to load properly.

**Comment by binwiederhier** [comment]
Duplicate of https://github.com/syncany/syncany/issues/508
