### ISSUE TITLE
Cannot create repo

### ISSUE THREAD

**Issue by mapomme1108** [syncany/syncany#486]
Hello,

I am new to syncany.

I would like to synchronize files between a local folder and a folder on a server sftp

I choose "Connec to an existing online storage"

I enter the following information:
Hostname: the IP address of my SFTP server: xx.xxx.xx.xxx
Username: admin
Private key: I leave empty
Password: the password of my admin account
Path: /share/drive
Port: 22

The error message is:

"Connecting to repo for folder D: \ ... ERROR

Unable to connect to folder (code: 501)
The operation failed Entirely. An exception was thrown"

The message is the same regardless of the selected local folder

I don't know where is the error...

**Comment by pimotte** [comment]
Can you reinstall the plugin from this jar: https://get.syncany.org/dist/plugins/snapshots/sftp/syncany-plugin-sftp-0.4.6-alpha+SNAPSHOT.1506161015.git2058394.jar and see if the problem remains? If it does, can you give the full error messages and the specifics of your SFTP server config (OS/openssh version/authentication method)

**Comment by mapomme1108** [comment]
Hello pimotte,

I have reinstalled the sftp plugin from the jar and there is the same error
Here is the full error message :
"Connecting to repo for folder D: \ ... ERROR

Unable to connect to folder (code: 501)
The operation failed Entirely. An exception was thrown"

I have created the same repo with the ftp plugin.
Here is the full message when I try with the ftp plugin:
"Connecting to repo for folder D:\ ...ERROR

Unable to connect to folder (code: 502)
Testing the remote storage failed.

- Was the connection successful: YES
- Files can be created: YES
- Files can be written to: YES
- The target folder/repo exists: YES"

My SFTP server is a Qnap TS-231. The OS is QTS 4.1.3
I don't know the openssh version and the authentification method.

**Comment by binwiederhier** [comment]
Are you trying to `sy init` or `sy connect`? Can you post the full output when you do this on the command line: `sy init -d` or `sy connect -d`.

**Comment by mapomme1108** [comment]
I am not using the command line
I am using the GUI

**Comment by mapomme1108** [comment]
Hello,

I used both the GUI and the command line "sy up"
The two do not work: the GUI and command line run, but it does not work

**Comment by pimotte** [comment]
Can you give us the output from `sy up -d` to see what goes wrong?

**Comment by mapomme1108** [comment]
The command line "sy up -d" list all the files in the repo and finishes with :
"Sync up finished"

**Comment by pimotte** [comment]
That seems like it works. If you try it again without changing any files, does it report "Sync up skipped, no local changes."?

**Comment by mapomme1108** [comment]
yes it report "Sync up skipped, no local changes"

When I did the first "sy up", it list the files and then list the files that must be uploaded and these files were those I want to sync

Is it possible the files were synced in another folder?

**Comment by pimotte** [comment]
This means that everything went as expected. 

If you're thinking you will see them on the server, you won't, because they are encrypted and chopped into pieces. (See the [FAQ](https://syncany.readthedocs.org/en/latest/faq.html#can-i-use-syncany-to-sync-two-unencrypted-folders-can-i-mirror-two-folders)).

If you want to retrieve them from the server, install Syncany on another computer and Connect it to your SFTP server.

**Comment by mapomme1108** [comment]
Too bad, I thought that I will see the files on the server.

Do you know an alternative to Syncany with which one can see the files on the server?

I tried Pydio but I did not manage to run the synchronization

**Comment by pimotte** [comment]
You could run Syncany on the server as well, with a local repo, such that you can see the files in plaintext as well, though this kind of defeats the purpose of using Syncany in the first place.

Alternatives include: Using rsync over ssh, ownCloud, syncthing and sparkleshare.

**Comment by mapomme1108** [comment]
I use Syncthing; it's working fine.

Thanks for your help
