### ISSUE TITLE
API bug: Platform independent plugins are not provided to all platforms

### ISSUE THREAD

**Issue by pimotte** [syncany/syncany#495]
Apperently our API refuses to provide plugins to ARM users, which I consider discrimination. I am 99% sure this is a bug caused by our filtering procedures on the serverside.

Thanks to aslmx, who reported this through IRC.

**Comment by aslmx** [comment]
support :+1: 

thanks for looking into this!

**Comment by binwiederhier** [comment]
Fixed in https://github.com/syncany/syncany-website/commit/d6a0bb1e7476d62b7b051d34ed7f13deaad3f1fc

**Comment by binwiederhier** [comment]
This is obviously only a fix for ARM, but I would like to keep a tight control of what we allow/support.

**Comment by aslmx** [comment]
i can confirm it works (tested on my BananaPi with SFTP plugin). 
Plugin can now be installed with sy plugin install.

Thanks for making life easier :-)
