### ISSUE TITLE
sincronized folders - change connection plugin

### ISSUE THREAD

**Issue by sempreneicasini** [syncany/syncany#505]
Hi
here again for a new question.
A folder sincronized (with nas repository) by webdav plugin ... is it possible to change the connection mode for this folders? ... from webdav to local (on the fly??? ... ) ... ??? .. this without change anything on the repository nas??

**Comment by pimotte** [comment]
If you have accesss to it in a local way (mounted folder/otherwise) you can remove the ".syncany" folder and then connect (either through GUI or through the `connect' command) with the local plugin.

**Comment by sempreneicasini** [comment]
tnk you

**Comment by pimotte** [comment]
No problem:)
