### ISSUE TITLE
Full GUI client for linux/win - is it in development ?

### ISSUE THREAD

**Issue by xyz15** [syncany/syncany#510]
Hi, 
with today's termination notice from Wuala (sync terminated by Sept 30th) and dumbed down Spideroak&Tresorit services, that sacrificed real secure system for a quick buck, I believe we need SyncAny fully developed now more than ever! 

Problem is I would gladly switch my business files sync to syncany (formerly using Wuala, but been testing SyncAny for my private files sync for few months now - Nix&Win), but my colleagues are not tech savvy, so without full gui (nix/win) supporting the underlining daemon, I can not force them to use it. The second major problem is, they need to be able to access files from their android phones (I know, that is a whole another thing)...

So my question is - is GUI for nix/win in development ? Or in planning stages ? Is there someone actively working on it ? 

I would also like to ask, if devs plan to crowdfund to speed up further development ? Or do you have some funding to continue full time ? Maybe, devs could provide(resell) storage on e.g. AWS for a some monthly fee - so we users would be able to support your development ? 

Thanks devs very much in advance for your reply.
Let me wish you all the best and more!
Jeremy

**Comment by pimotte** [comment]
The full GUI for Windows/MacOS/Linux exists, functions, but is still undergoing development. You can get it by installing the gui plugin (`syncany plugin install gui`) or using one of the packages that includes it. 

Android support should be doable at some point, but has not been started, and it is unlikely that it will before the core goes into beta.

As far as I know there exist no plans to do crowdfunding at this point in time.

**Comment by pimotte** [comment]
Since all the questions have been answered, I'm going to close this. Feel free to reopen if you have more questions.
