### ISSUE TITLE
Unable to "sy up" after incomplete upload (invalid hex in XML database)

### ISSUE THREAD

**Issue by vonronne** [syncany/syncany#520]
I had a large directory (many gigabytes of photos) that I was trying to upload into a new syncany repository in an S3 bucket.  (BTW, this is another bug, but the dialog for creating S3 repositories; doesn't have an option for the us-east region, so I had to manually set the endpoint.)  

Unfortunately, I didn't have enough time for it to finish, and had to shutdown the machine in the middle of the upload, and it sat for a few days before I could finish the upload. In the meantime, I did an sy connect another machine, and sy GUI may ran on the original machine.  Then, I tried an "sy down" and "sy up" on the original machine to finish the upload.  I get the following error:

$ sy up
Checking remote changes ...Error: java.lang.IllegalArgumentException: hexBinary needs to be even-length: 1fdae0acdfc6e2bb2bd757af26e6a6d198ec3dd
       Refer to help page using '--help'.

Apparently a hex number was in the process of being written when the upload was interrupted and now syncany dies during parsing and can't even attempt to recover.  

"sy up -d" output to follow.

**Comment by vonronne** [comment]
Here's a sanitized version of the output from "sy up -d":

25-9-15 9:57:15.671 | CommandLineClie | main           | INFO : Application version: 0.4.6-alpha
25-9-15 9:57:15.674 | InternalEventBu | main           | INFO : Event bus 'LocalEventBus': Registering StatusCommand (org.syncany.cli.StatusCommand@58017a75) ...
25-9-15 9:57:15.682 | org.syncany.plu | main           | FINE : Validating required fields
25-9-15 9:57:15.742 | S3TransferManag | main           | INFO : Endpoint is set, assuming s3 non-standard
25-9-15 9:57:15.742 | TransferManager | main           | INFO : Building S3TransferManager from config 'Pictures' ...
25-9-15 9:57:15.743 | TransferManager | main           | INFO : - With feature ReadAfterWriteConsistent
25-9-15 9:57:15.743 | TransferManager | main           | INFO : - With feature Retriable
25-9-15 9:57:15.743 | TransferManager | main           | FINE : - Checking if selected features supported ...
25-9-15 9:57:15.748 | TransferManager | main           | FINE : - Checking for duplicate features ...
25-9-15 9:57:15.749 | TransferManager | main           | FINE : - Checking required feature TransactionAware in S3TransferManager ...
25-9-15 9:57:15.755 | TransferManager | main           | FINE : - Checking required feature Retriable in S3TransferManager ...
25-9-15 9:57:15.756 | TransferManager | main           | FINE : - Wrapping TransferManager S3TransferManager in ReadAfterWriteConsistentFeatureTransferManager
25-9-15 9:57:15.757 | TransferManager | main           | FINE : - Wrapping TransferManager ReadAfterWriteConsistentFeatureTransferManager in RetriableFeatureTransferManager
25-9-15 9:57:15.758 | org.syncany.plu | main           | FINE : Validating required fields
25-9-15 9:57:15.760 | S3TransferManag | main           | INFO : Endpoint is set, assuming s3 non-standard
25-9-15 9:57:15.760 | TransferManager | main           | INFO : Building S3TransferManager from config 'Pictures' ...
25-9-15 9:57:15.760 | TransferManager | main           | INFO : - With feature ReadAfterWriteConsistent
25-9-15 9:57:15.761 | TransferManager | main           | INFO : - With feature Retriable
25-9-15 9:57:15.761 | TransferManager | main           | INFO : - With feature PathAware
25-9-15 9:57:15.761 | TransferManager | main           | INFO : - With feature TransactionAware
25-9-15 9:57:15.763 | TransferManager | main           | FINE : - Checking if selected features supported ...
25-9-15 9:57:15.763 | TransferManager | main           | FINE : - Checking for duplicate features ...
25-9-15 9:57:15.764 | TransferManager | main           | FINE : - Checking required feature TransactionAware in S3TransferManager ...
25-9-15 9:57:15.764 | TransferManager | main           | FINE : - Checking required feature Retriable in S3TransferManager ...
25-9-15 9:57:15.764 | TransferManager | main           | FINE : - Wrapping TransferManager S3TransferManager in ReadAfterWriteConsistentFeatureTransferManager
25-9-15 9:57:15.765 | TransferManager | main           | FINE : - Wrapping TransferManager ReadAfterWriteConsistentFeatureTransferManager in RetriableFeatureTransferManager
25-9-15 9:57:15.765 | TransferManager | main           | INFO : - SKIPPING unsupported optional feature PathAware
25-9-15 9:57:15.765 | TransferManager | main           | FINE : - Wrapping TransferManager RetriableFeatureTransferManager in TransactionAwareFeatureTransferManager
25-9-15 9:57:15.770 | DatabaseConnect | main           | INFO : Loading database driver org.hsqldb.jdbcDriver ...
25-9-15 9:57:16.141 | DatabaseConnect | main           | INFO : Found 12 tables.
25-9-15 9:57:16.150 | UpOperation     | main           | INFO : 
25-9-15 9:57:16.151 | UpOperation     | main           | INFO : Running 'Sync up' at client QiYHQTvtDMLWlcTfxkJE ...
25-9-15 9:57:16.151 | UpOperation     | main           | INFO : --------------------------------------------
25-9-15 9:57:16.151 | InternalEventBu | main           | INFO : Event bus 'LocalEventBus': Posting event UpStartSyncExternalEvent (org.syncany.operations.daemon.messages.UpStartSyncExternalEvent@58e9b710) ...
25-9-15 9:57:16.159 | DatabaseConnect | main           | INFO : Found 12 tables.
25-9-15 9:57:16.160 | StatusOperation | main           | INFO : 
25-9-15 9:57:16.160 | StatusOperation | main           | INFO : Running 'Status' at client QiYHQTvtDMLWlcTfxkJE ...
25-9-15 9:57:16.160 | StatusOperation | main           | INFO : --------------------------------------------
25-9-15 9:57:16.160 | StatusOperation | main           | INFO : Querying current file tree from database ...
25-9-15 9:57:16.161 | InternalEventBu | main           | INFO : Event bus 'LocalEventBus': Posting event StatusStartSyncExternalEvent (org.syncany.operations.daemon.messages.StatusStartSyncExternalEvent@63a742e3) ...
25-9-15 9:57:16.849 | StatusOperation | main           | INFO : Analyzing local folder /home/********/Pictures ...
25-9-15 9:57:16.855 | StatusOperation | main           | FINE : - Ignoring file (syncany app-related): .syncany
25-9-15 9:57:17.401 | StatusOperation | main           | FINE : - New file: *************

[this line repeated with slightly different times for about 7,000 different files/directories]

25-9-15 9:57:18.808 | InternalEventBu | main           | INFO : Event bus 'LocalEventBus': Posting event StatusEndSyncExternalEvent (org.syncany.operations.daemon.messages.StatusEndSyncExternalEvent@6e030872) ...
25-9-15 9:57:18.809 | AbstractTransfe | main           | INFO : Looking for other running remote operations ...
25-9-15 9:57:18.809 | S3TransferManag | main           | INFO : Endpoint is set, assuming s3 non-standard
25-9-15 9:57:18.847 | S3TransferManag | main           | INFO : Endpoint is set, assuming s3 non-standard
25-9-15 9:57:18.848 | S3TransferManag | main           | INFO : Using non-standard endpoint, ignoring region.
25-9-15 9:57:19.912 | S3TransferManag | main           | FINE : - Downloading from bucket ********: S3Object [key=**********, bucket=***********, lastModified=Sun Sep 20 16:43:26 EDT 2015, dataInputStream=org.jets3t.service.impl.rest.httpclient.HttpMethodReleaseInputStream@71046bb7, Metadata={ETag="c6b99110a1ee522f0a70a7689e3ecf0c", __complete__={x-amz-request-id=E9993EE04D5135CD, ETag="c6b99110a1ee522f0a70a7689e3ecf0c", Date=Fri Sep 25 09:57:20 EDT 2015, Content-Length=2701, Last-Modified=Sun Sep 20 16:43:26 EDT 2015, x-amz-id-2=73NMmYGG+OfSnNwuP63YTSW++aQ44yfFC05TXcP/odcAPsg60RtTFTEA1jwgGmUi, Content-Type=application/x-syncany, Accept-Ranges=bytes, Server=AmazonS3}, Date=Fri Sep 25 09:57:20 EDT 2015, Content-Length=2701, __service__={id-2=73NMmYGG+OfSnNwuP63YTSW++aQ44yfFC05TXcP/odcAPsg60RtTFTEA1jwgGmUi, request-id=E9993EE04D5135CD}, id-2=73NMmYGG+OfSnNwuP63YTSW++aQ44yfFC05TXcP/odcAPsg60RtTFTEA1jwgGmUi, request-id=E9993EE04D5135CD, Last-Modified=Sun Sep 20 16:43:26 EDT 2015, Content-Type=application/x-syncany, __user__={}}] ...
25-9-15 9:57:19.924 | CipherSession   | main           | FINE : - Created NEW READ secret key HmacSHA256, and added to cache, with salt ************************
25-9-15 9:57:19.926 | CipherSession   | main           | FINE : - Created NEW READ secret key AES, and added to cache, with salt ************************
25-9-15 9:57:19.984 | AbstractTransfe | main           | INFO : - Action file outdated; ignoring RemoteFile[name=action-cleanup-bjgwXIGJkQIqmdviknaM-1443073967723]
25-9-15 9:57:19.989 | DatabaseConnect | main           | INFO : Found 12 tables.
25-9-15 9:57:19.989 | LsRemoteOperati | main           | INFO : 
25-9-15 9:57:19.990 | LsRemoteOperati | main           | INFO : Running 'Remote Status' at client QiYHQTvtDMLWlcTfxkJE ...
25-9-15 9:57:19.990 | LsRemoteOperati | main           | INFO : --------------------------------------------
25-9-15 9:57:19.990 | InternalEventBu | main           | INFO : Event bus 'LocalEventBus': Posting event LsRemoteStartSyncExternalEvent (org.syncany.operations.daemon.messages.LsRemoteStartSyncExternalEvent@7ed32b58) ...
25-9-15 9:57:19.999 | LsRemoteOperati | main           | INFO : Retrieving remote database list.
25-9-15 9:57:20.055 | S3TransferManag | main           | INFO : Cannot create instance of DatabaseRemoteFile for object cleanup-1; maybe invalid file name pattern. Ignoring file.
25-9-15 9:57:20.174 | S3TransferManag | main           | FINE : - Downloading from bucket ********: S3Object [key=*******, bucket=***********, lastModified=Sun Sep 20 16:43:26 EDT 2015, dataInputStream=org.jets3t.service.impl.rest.httpclient.HttpMethodReleaseInputStream@4104ebd, Metadata={ETag="c6b99110a1ee522f0a70a7689e3ecf0c", __complete__={x-amz-request-id=14BBCD18C265BF63, ETag="c6b99110a1ee522f0a70a7689e3ecf0c", Date=Fri Sep 25 09:57:21 EDT 2015, Content-Length=2701, Last-Modified=Sun Sep 20 16:43:26 EDT 2015, x-amz-id-2=9rRsQHgZL8Z/y7pdcwK3vxqNBixVwKLWKZUqgDICsPTMgbsBxM8Q2QDxeSGf8iev, Content-Type=application/x-syncany, Accept-Ranges=bytes, Server=AmazonS3}, Date=Fri Sep 25 09:57:21 EDT 2015, Content-Length=2701, __service__={id-2=9rRsQHgZL8Z/y7pdcwK3vxqNBixVwKLWKZUqgDICsPTMgbsBxM8Q2QDxeSGf8iev, request-id=14BBCD18C265BF63}, id-2=9rRsQHgZL8Z/y7pdcwK3vxqNBixVwKLWKZUqgDICsPTMgbsBxM8Q2QDxeSGf8iev, request-id=14BBCD18C265BF63, Last-Modified=Sun Sep 20 16:43:26 EDT 2015, Content-Type=application/x-syncany, __user__={}}] ...
25-9-15 9:57:20.177 | CipherSession   | main           | FINE : - Using CACHED READ secret key HmacSHA256, with salt ************************
25-9-15 9:57:20.178 | CipherSession   | main           | FINE : - Using CACHED READ secret key AES, with salt ************************
25-9-15 9:57:20.223 | InternalEventBu | main           | INFO : Event bus 'LocalEventBus': Posting event LsRemoteEndSyncExternalEvent (org.syncany.operations.daemon.messages.LsRemoteEndSyncExternalEvent@4ce2fbd3) ...
25-9-15 9:57:20.224 | UpOperation     | main           | INFO : No remote changes, ready to upload.
25-9-15 9:57:20.225 | ActionFileHandl | main           | INFO : Starting action for RemoteFile[name=action-up-QiYHQTvtDMLWlcTfxkJE-1443189435767] ...
25-9-15 9:57:20.225 | ActionFileHandl | main           | INFO : Uploading action file: RemoteFile[name=action-up-QiYHQTvtDMLWlcTfxkJE-1443189435767]
25-9-15 9:57:20.226 | S3TransferManag | main           | INFO : Endpoint is set, assuming s3 non-standard
25-9-15 9:57:20.227 | S3TransferManag | main           | INFO : Endpoint is set, assuming s3 non-standard
25-9-15 9:57:20.227 | S3TransferManag | main           | INFO : Using non-standard endpoint, ignoring region.
25-9-15 9:57:20.227 | S3TransferManag | main           | FINE : - Uploading to bucket ********: StorageObject [key=actions/action-up-QiYHQTvtDMLWlcTfxkJE-1443189435767, lastModified=null, dataInputStream=java.io.FileInputStream@5c3e95fd, Metadata={Content-Length=0, Content-Type=application/x-syncany}] ...
25-9-15 9:57:20.557 | ReadAfterWriteC | main           | FINE : RemoteFile[name=action-up-QiYHQTvtDMLWlcTfxkJE-1443189435767] exists on the remote side
25-9-15 9:57:20.558 | ActionFileHandl | main           | INFO : Scheduling action renewal task for every 2 minutes, for RemoteFile[name=action-up-QiYHQTvtDMLWlcTfxkJE-1443189435767] ...
25-9-15 9:57:20.561 | UpOperation     | main           | INFO : Found local transaction to resume.
25-9-15 9:57:20.562 | UpOperation     | main           | INFO : Attempting to find transactionRemoteFile
25-9-15 9:57:20.574 | DatabaseXmlSeri | main           | INFO : - Loading database (FULL) from file /home/********/Pictures/.syncany/state/transaction-database.0000000081.xml ...
25-9-15 9:57:20.586 | CommandLineClie | main           | SEVE : Command org.syncany.cli.UpCommand@33a9447c FAILED. 
java.io.IOException: java.lang.IllegalArgumentException: hexBinary needs to be even-length: 1fdae0acdfc6e2bb2bd757af26e6a6d198ec3dd
	at org.syncany.database.dao.DatabaseXmlSerializer.load(DatabaseXmlSerializer.java:119)
	at org.syncany.operations.up.UpOperation.attemptResumeDatabaseVersions(UpOperation.java:771)
	at org.syncany.operations.up.UpOperation.execute(UpOperation.java:151)
	at org.syncany.cli.UpCommand.execute(UpCommand.java:56)
	at org.syncany.cli.CommandLineClient.runLocally(CommandLineClient.java:392)
	at org.syncany.cli.CommandLineClient.runCommand(CommandLineClient.java:382)
	at org.syncany.cli.CommandLineClient.start(CommandLineClient.java:198)
	at org.syncany.Syncany.main(Syncany.java:52)
Caused by: java.lang.IllegalArgumentException: hexBinary needs to be even-length: 1fdae0acdfc6e2bb2bd757af26e6a6d198ec3dd
	at javax.xml.bind.DatatypeConverterImpl.parseHexBinary(DatatypeConverterImpl.java:446)
	at javax.xml.bind.DatatypeConverter.parseHexBinary(DatatypeConverter.java:357)
	at org.syncany.util.StringUtil.fromHex(StringUtil.java:113)
	at org.syncany.database.ObjectId.parseObjectId(ObjectId.java:66)
	at org.syncany.database.ChunkEntry$ChunkChecksum.parseChunkChecksum(ChunkEntry.java:102)
	at org.syncany.database.dao.DatabaseXmlParseHandler.startElement(DatabaseXmlParseHandler.java:109)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509)
	at com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(AbstractXMLDocumentParser.java:182)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(XMLDocumentFragmentScannerImpl.java:1343)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2786)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:648)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:332)
	at javax.xml.parsers.SAXParser.parse(SAXParser.java:195)
	at org.syncany.database.dao.DatabaseXmlSerializer.load(DatabaseXmlSerializer.java:116)
	... 7 more

**Comment by pimotte** [comment]
Since it looks to fail in loading `.syncany/state/transaction-database.0000000081.xml`, this is a problem with resumption. You can restart the upload by using `syncany up --no-resume`. 

The solution on our side would be to automatically clean up resumed transactions. I thought we did that, but apparently not good enough. Can you manually inspect the the above file to see if it indeed is incomplete at the checksum that throws the error?

**Comment by vonronne** [comment]
Visually, the database looks like OK XML.  (It doesn't break off at the 1fdae0acdfc6e2bb2bd757af26e6a6d198ec3dd.)  

But xmllint does find unmatched tags:

.../state$ xmllint transaction-database.0000000081.xmltransaction-database.0000000081.xml:869: parser error : Opening and ending tag mismatch: chunkRef line 858 and multiChunk
				</multiChunk>
				             ^
transaction-database.0000000081.xml:1600: parser error : Opening and ending tag mismatch: chunkRefs line 857 and multiChunks
			</multiChunks>
			              ^
transaction-database.0000000081.xml:2229: parser error : Opening and ending tag mismatch: multiChunk line 856 and databaseVersion
		</databaseVersion>
		                  ^
transaction-database.0000000081.xml:2230: parser error : Opening and ending tag mismatch: multiChunks line 469 and databaseVersions
	</databaseVersions>
	                   ^
transaction-database.0000000081.xml:2231: parser error : Opening and ending tag mismatch: databaseVersion line 4 and database
</database>4f3b2be0f096f527f38c59cab6"/>
           ^
transaction-database.0000000081.xml:2249: parser error : error parsing attribute name
						<c85c274e64561c49c97b608c6516b"/>
						                              ^
transaction-database.0000000081.xml:2249: parser error : attributes construct error
						<c85c274e64561c49c97b608c6516b"/>
						                              ^
transaction-database.0000000081.xml:2249: parser error : Couldn't find end of Start Tag c85c274e64561c49c97b608c6516b line 2249
						<c85c274e64561c49c97b608c6516b"/>
						                              ^
transaction-database.0000000081.xml:2567: parser error : Opening and ending tag mismatch: databaseVersions line 3 and chunkRefs
					</chunkRefs>
					            ^
transaction-database.0000000081.xml:2568: parser error : Opening and ending tag mismatch: database line 2 and fileContent
				</fileContent>
				              ^
transaction-database.0000000081.xml:2569: parser error : Extra content at the end of the document
				<fileContent checksum="a0b82e77c3c0ca8abc7e7cb22387e059122241cb" size="20864
				^

**Comment by vonronne** [comment]
[Github doesn't want to let me attach the complete file.]

Here's what it looks like around line 469:

                                <chunk checksum="e7a95a83f27a052444596ad3c2c4620c3a453f15" size="524288"/>
                                <chunk checksum="c7698fd8d163546db77ae252bffa352b5ecb4963" size="524288"/>
                                <chunk checksum="c66b010e3bad8e8d171681301cda9ad28fdd2252" size="524288"/>
                                <chunk checksum="64bc4410f9537e84f4d42e81eea553335ea75e14" size="524288"/>
                                <chunk checksum="6088706a67ec3b117feeefc2f2fbb69a3e02f0c3" size="524288"/>
                        </chunks>
                        <multiChunks>
                                <multiChunk id="2c2966f2e988e8e909e88ec1a4802ba1cd388e43" size="4194304">
                                        <chunkRefs>
                                                <chunkRef ref="b0c253b2dfa1a8f316acf6fa669ac0c298c120b5"/>
                                                <chunkRef ref="dcf5cc22020b7d0fdb2e7cd418f487d535435e3e"/>
                                                <chunkRef ref="7eee5f6e58dd16b265ac182cfeba42681b1642b7"/>


Here's what it looks like around line 858:

                                <multiChunk id="ad7a084dccc04c0ad2ff13342ff040a4b4a011d6" size="4194304">
                                        <chunkRefs>
                                                <chunkRef ref="8782fee2798328447ad09f22370e8" size="4194304">
                                        <chunkRefs>
                                                <chunkRef ref="1188d3ad6ae6de598b7b19632b92536d817926d6"/>
                                                <chunkRef ref="ff9d6abbabd3367ddb6aa45aa4f88eded9f0b86e"/>
                                                <chunkRef ref="9ecf4e0b6f1a75b16de172f5b6022a52f8cb5645"/>
                                                <chunkRef ref="6c2ef90c1645f24368c123aaf9b5f67858cfc66b"/>
                                                <chunkRef ref="018f9017bc7dc4c59f2aaa8d497ad3f942b82a8c"/>
                                                <chunkRef ref="b8d22a9ed5defc342b254faadedfe30dd8ffa13c"/>
                                                <chunkRef ref="1146ceb8eefaee7316fa2a702a766a42ff2ec0a7"/>
                                                <chunkRef ref="c605f5414f9c31e89f199a4407a7583c79b5e8b2"/>
                                        </chunkRefs>
                                </multiChunk>

Here's what it looks like around 229:

                                                <fileVersion version="1" type="FILE" status="NEW" path="***" size="314154583" lastModified="1429057725000" updated="1442778054292" checksum="882fce1a89c963d03dd5fa7ca0651e56f2794f36" dosattrs="--a-" posixperms="rw-rw-r--"/>
                                        </fileVersions>
                                </fileHistory>
                        </fileHistories>
                </databaseVersion>
        </databaseVersions>
</database>4f3b2be0f096f527f38c59cab6"/>
                                                <chunkRef ref="519d3d75f0884c8bfe3474a107a289a40a114c61"/>
                                                <chunkRef ref="d00336541cbb3cdc63b76e66aa95ce108bde8ed0"/>
                                                <chunkRef ref="ef326e85acdc3c5aca3692fd76fec4fa05d704dd"/>
                                                <chunkRef ref="fdf058503961936595dfb9bfe611651268056b0c"/>
                                                <chunkRef ref="4fd5c26920dd232d4158ce29fc740aa86f74dbf9"/>
                                                <chunkRef ref="2145f18539f97ec5c118bacc0a07ee17d9d89ab6"/>

Here's what it looks like around 2567:

                                                <chunkRef ref="dd392ecf817be3c52358279516f5d35b0350b9dc"/>
                                                <chunkRef ref="10db6ed62d89e3f8c084acfe6f696faea2cdc3d2"/>
                                        </chunkRefs>
                                </fileContent>
                                <fileContent checksum="a0b82e77c3c0ca8abc7e7cb22387e059122241cb" size="2086424">
                                        <chunkRefs>
                                                <chunkRef ref="49e2da1c79f5fb5ba02dc834d8cfda55d2dd090f"/>
                                                <chunkRef ref="434be0e61e387b96cdc6e3cdc1cfbf3847d245e0"/>

**Comment by vonronne** [comment]
Github's markdown processing is butchering the database file content.

The interesting thing in the around line 2229, is that the hex 4f3b2... starts immediately after  the database closing tag: </database>4f3b2be0f096f527f38c59cab6" /> 

Maybe two concurrent writers without proper locking / fsync?  

I suppose I should mention that I'm using btrfs.

**Comment by vonronne** [comment]
As far as the invalid hex goes, which is at line 216, however.  That looks fine, except that it is missing one character:

                                <chunk checksum="2247c47015380a71c04f70bbb898b05e07622bda" size="524288"/>
                                <chunk checksum="1fdae0acdfc6e2bb2bd757af26e6a6d198ec3dd" size="524288"/>
                                <chunk checksum="9dba3d31a47c90c577a6ecc77188fc4ca2033af3" size="524288"/>

**Comment by binwiederhier** [comment]
https://github.com/syncany/syncany/commit/e871fcec43ff78e3960c2b9ef5d7d60c9abe2db1 fixes this issue by not resuming if the local transaction files are corrupt.
