### ISSUE TITLE
Version 0.4.6 - JRELoadError - OS X El Capitan 10.11.1 

### ISSUE THREAD

**Issue by dakkusingh** [syncany/syncany#526]
Any one else have this error when opening the app?
I have 0.4.6 version of the app.

**Comment by pimotte** [comment]
Could you try running `sy gui -d` from the command line and posting the full stacktrace

**Comment by 0asa** [comment]
I had the same issue. I installed the Java JRE and now it is working.

I did it this way: 

1. install [Homebrew](http://brew.sh) (if not done already).
2. `brew install Caskroom/cask/java`
3. For the CLI: `brew install https://get.syncany.org/homebrew/syncany.rb` (might be optional).

@pimotte I get the following when trying to run the command you suggested:

```
$ sy gui -d
Error: Given command is unknown: gui
       Refer to help page using '--help'.
```

**Comment by pimotte** [comment]
Ah, yes, homebrew doesn't include the GUI.

If installing JRE makes it work, I'm going to close this as duplicate and link it to #478.

**Comment by SG5** [comment]
Still have this error.
Have tried install JRE and JDK.

**Comment by shimj** [comment]
The same error
