### ISSUE TITLE
Default .syignore not ignoring files recursively

### ISSUE THREAD

**Issue by sevnlabs** [syncany/syncany#544]
I had some trouble with the default .syignore file (requested in #393), because files like .DS_Store had only been ignored in the top level folder... the .DS_Store **files in nested folders have not been ignored** und caused me a lot of trouble when using the share with other people...

After checking the source code and java documentation I found a better way of ignoring the files **recursively**:

Instead of writing:

> .DS_Store
> .ds_store

you should write:

> regex:(.\*)\\.DS_Store
> regex:(.\*)\\.ds_store

Now the .DS_Store files are ignored **recursively**!

**This should be corrected for the default .syignore!**

**Comment by jgoestl** [comment]
This is fixed with merge https://github.com/syncany/syncany/pull/555

**Comment by pimotte** [comment]
:+1:
