### ISSUE TITLE
Re-connecting a folder fails (SFTP Plugin, snapshot version)

### ISSUE THREAD

**Issue by nickk-** [syncany/syncany#556]
Currently testing Syncany. 

**Setup:**

- ACER Aspire Switch 10 FHD (1920 x 1200, 2 GB RAM)
- Java SE RE 1.8.0_71-b15
- SY w/ GUI 0.4.7-alpha. 
- SFTP Plugin (--snapshot, as SFTP account uses non-certificate based authentication)

**Steps to reproduce:**
- _Add a folder_ using the Wizard
- _Create a new online storage_, folder "desktopwiki.shared" (SFTP storage backend)
- Use it. 
- "desktopwiki.shared" -> _Remove folder_

- _Add a folder_ using the Wizard
- _Connect to an existing online storage_
- Result: Fails (see screenshot)
- Variant: Remove .syncany in "desktopwiki.shared", repeat procedure. Result: Fails 
- Variant: Remove all others files and subfolders in "desktopwiki.shared", repeat procedure. Result: Fails 

![2016-02-06 syncany github issue reconnect](https://cloud.githubusercontent.com/assets/6384352/12865723/ad575d4e-ccb4-11e5-944e-0ca0e664930b.png)

**Comment by pimotte** [comment]
By "remove Syncany folder" you mean delete it on the filesystem, right, not removing from the daemon through the Syncany GUI?

**Comment by nickk-** [comment]
Ah, sorry - that was not clear enough. 

By "'desktopwiki.shared' -> Remove folder" I documented what I did with the GUI, so that was removing the folder from the daemon. NB: As I am new to Syncany, I wasn't quite sure what that menu item implied. I had to look at the file system to see that the data was still there (which was what I would expect, but "remove" sounded like a non idem-potent choice, maybe "disconnect" would be a better choice of words) 

In the Variants I described later, I actually removed data from the local file system.

**Comment by pimotte** [comment]
Okay, so the underlying problem is probably that we attached folders in the daemon config, and I'm guessing we don't verify that those folders are actually syncany folders. We probably want to alter the check to detect if the folder actually exists and is a syncany folder in addition to the check if it's in the daemon config.

**Comment by nickk-** [comment]
Correction: Test case probably tainted by not correctly deleting the .syncany directory. 
"Connect to an existing online storage" is not the correct way to re-connect a formerly connected folder. "Add an existing Syncany folder" is. 

Suggesting to alter that item's description by adding ", i.e. re-connecting a folder for synchronisation via Syncany" or the like.

**Comment by nickk-** [comment]
Cannot reproduce, thus closing the issue.
