### ISSUE TITLE
cannot import to intellij-idea

### ISSUE THREAD

**Issue by Kidlike** [syncany/syncany#573]
![intellij-import-syncany](https://cloud.githubusercontent.com/assets/5050182/13894787/c74efb92-ed63-11e5-8c6b-8aeca05a1390.png)

Getting this when trying to import the syncany/syncany project.
I'm new to gradle.
Why does intellij try to import 15 modules?
If it was maven, it should be 4 (the parent module + 3 children); right ?

**Comment by Kidlike** [comment]
So, turns out that the maven way of working doesn't apply here.

I had to include this to the parent build.gradle:

```
allprojects {
    apply plugin: 'idea'
}
```

And run:
./gradlew idea

Which generates the .iml files (intellij project files), which then can be used to just Open the project. (and not import, or create).

The mappings of the source directories (sources, resources, test sources, test resources) isn't perfect.
(The structure of this project is a bit weird though...)
But the dependencies are loaded correctly.
Also the Gradle window doesn't show up the first time the generated project is opened.
But the next time, Intellij asks you if you want to add it. (I just left all options as they were, and then clicked deselect all, on the module selection; everything worked).

After this short experience with Gradle, I can say that I like the flexibility that it offers, but I wouldn't change maven. I don't see the point of loosing the conventions it offers, that make all software around it work perfectly.

**Comment by pimotte** [comment]
As of now you should be able to just open the root build.gradle file.
