### ISSUE TITLE
gui branch is not the latest?

### ISSUE THREAD

**Issue by xiaoyao5137** [syncany/syncany#594]
I hava pull the latest branch 'gui', but eclipse has reported some errors NoClassFoundException.
I also try pull the latest branch 'gui-orig', but this branch has some problems, 'preference' view has a lot less such as 'plugins'.
Is this branch latest one?

**Comment by pimotte** [comment]
The gui branch is really old, afaik. The code to the current GUI is contained within this repo: https://github.com/syncany/syncany-plugin-gui
