### ISSUE TITLE
can't install any plugin on windows

### ISSUE THREAD

**Issue by adnoh** [syncany/syncany#600]
hello guys, just tried to play around with syncany.
installed on windows 10 with the current jre 64 bit
getting while debugging:
"java.exe" "-Dfile.encoding=utf-8" "-Xmx512M"    -classpath "D:\Progs\Syncany\bin\..\lib\*;C:\Users\BLAAA\AppData\Roaming\Syncany\plugins\lib\*" org.syncany.Syncany plugin install sftp Installing plugin from https://get.syncany.org/dist/plugins/releases/sftp/syncany-plugin-sftp-0.4.5-alpha.jar ...**Error: java.lang.IllegalAccessException: Can not set static final boolean field javax.crypto.JceSecurity.isRestricted to java.lang.Boolean**
       Refer to help page using '--help'.

**Comment by pimotte** [comment]
This should be fixed in the latest release. If you can confirm it still exists in 0.4.9, then feel free to reopen this.
