### ISSUE TITLE
Recent release breaks compatibility to Java 7

### ISSUE THREAD

**Issue by streckus** [syncany/syncany#601]
On a system with Linux Mint 17.2 and openjdk-7-jre installed, I get the following error with syncany 0.4.9:
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/syncany/Syncany : Unsupported major.minor version 52.0 [...]

A quick search reveals that this error means that the package was compiled under Java 8 (version 52.0) and thus can't be run under the lower version 51.0 (Java 7). Release syncany 0.4.7 was working fine.

**Comment by pimotte** [comment]
We switched to 1.8 to enable Cobertura to stay working. The 0.4.8 release contains some minor fixes and a major bugfix for the 1.8 jdk. Feel free to stick with 0.4.7. I'm personally not really inclined to keep supporting jdk-7. Is 8 not available?

**Comment by streckus** [comment]
1.8 isn't available in the standard repositories with Mint 17.2 but I found instructions to install it, so it is working fine now. I just opened this because I thought you might want to keep compatibility to jdk-7.

**Comment by pimotte** [comment]
Thank you:) It's good to be aware of this since it means we should probably bump the dependencies. I'll leave this open as a reminder to do that, but I won't personally do any work to keep jdk-7 supported.
