### ISSUE TITLE
sy and syncany startup scripts don't work with other shells than bash anymore

### ISSUE THREAD

**Issue by apoleon** [syncany/syncany#602]
Hi,

newer versions of gradle (3.2.1+) will change the shebang of sy.sh and syncany.sh to

#!/usr/bin/env sh

from

#!/usr/bin/env bash

The latter used to work even when zsh was the default shell. There might be a configuration option for the gradle task "createStartScript" to modifiy the shebang but perhaps it is easier to avoid bash specific expressions in gradle/gradle/application.distribution.gradle.

I made the following changes and all error messages are gone when executing the start script on Linux.

-		unixClassPathCommands += "	if [[ \$LIB_GLOBAL_BASENAME == syncany-plugin-*.jar ]]; then\n"
+		unixClassPathCommands += "	if [ \"\$LIB_GLOBAL_BASENAME\" = syncany-plugin-*.jar ]; then\n"

**Comment by pimotte** [comment]
While the gradle we use in the build is something like version 1.11ish since we haven't really had a reason to upgrade, I'd be more than happy to take this change. Would you like to make a PR with this?

**Comment by pimotte** [comment]
Closed by #603
