### ISSUE TITLE
Dropbox Plugin -  No token was received in the given time interval

### ISSUE THREAD

**Issue by ghost** [syncany/syncany#607]
Hi,

I received of the Dropbox a auth error message and app not receive the token:

> "This app is unable to link additional users because it has been frozen pending review."

Syncany url :  

> https://www.dropbox.com/1/oauth2/authorize?locale=en&client_id=dlg8wdfpf3xa5jv&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A6462%2Fdropbox%2F&state=xBUCksSg8EIchfkhXNVRjA%3D%3D''

Thanks,

PS.: Sorry my horrible english. =)

**Comment by pimotte** [comment]
Thank you for your bug report. This is a duplicate of #521. Feel free to use the work-around there. Closing this.

**Comment by nielsonsantana** [comment]
I getting same error after try sync Dropbox.
"This app is unable to link additional users because it has been frozen pending review."
