### ISSUE TITLE
Code 502

### ISSUE THREAD

**Issue by andresgarcia0313** [syncany/syncany#622]
in another team I try to connect and:

Initializing repo for folder /home/andres/Escritorio/ArchivosSyncTestFTP ...ERROR

Unable to initialize folder (code: 502)
Testing the remote storage failed.

- Was the connection successful: YES
- Files can be created: YES
- Files can be written to: YES
- The target folder/repo exists: YES

**Comment by tinne** [comment]
Duplocate to #589.
