### ISSUE TITLE
Deprecated Gradle features were used in this build, making it incompatible with Gradle

### ISSUE THREAD

**Issue by BakasuraRCE** [syncany/syncany#632]
Hi,

When I try to compiling from source I get this:

`Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.`

**Comment by pimotte** [comment]
If you use ./gradlew you will use the gradle wrapper which is currently at 4.10. 

I would also accept a PR that updates gradle to 5 and finds replacements for the deprecated stuff we use.
